// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: script.proto

// Package script.v1 is how a program that wants LSL run asks something
// else to run it.
//
// The programs are slrun and slbench: they write a script, put it
// somewhere it can run, watch what it says, and want to know whether it
// compiled, whether it faulted and whether it got to the end.  None of
// that is particular to Second Life.  The same script can be run by the
// eLSL simulator with no grid at all, or by a viewer driven from
// outside, or by a client holding a real grid session -- and the caller
// should not have to be written three times to say so.
//
// So this is the seam.  A backend is anything that can be handed a
// script and made to answer these questions, and it lives wherever it
// likes: in this repository, beside the simulator, or beside a viewer.
//
// # What a backend owns and what a caller owns
//
// The backend owns everything that would break if the caller restarted:
// the grid session or the viewer, the objects a script runs in, which
// of them are busy, and the queue for them when they all are.  The
// caller owns the script and what its output means.
//
// That division is why a lease is a stream rather than a pair of calls.
// A caller that dies mid-benchmark must not leave objects held forever,
// and no timeout is a good answer to that: too short and a long run
// loses its objects, too long and a crash blocks the pool.  A stream
// answers exactly: the objects are held while the caller is there.
//
// # What is deliberately not here
//
// Rezzing, linking, texturing, inventory.  A script runs inside an
// object and the backend supplies one; how it came to exist is the
// backend's business.  The simulator has no prims, the viewer has slot
// files, a grid client rezzes and wears things, and a caller that had
// to know which would be back to being written three times.
//
// Nor is there anything for reading state back out of an object.  A
// benchmark that wants a number from the last run has the script say
// it, which works everywhere; anything else would be an interface to
// linkset data, which two of the three backends do not have.
//
// # Compatibility
//
// What is promised is the wire.  A field number is never reused, and a
// field never changes type: a new field takes a new number, and a field
// that is retired keeps its number reserved.  A field one side does not
// know is zero to it, so every new field is defined so that zero means
// what a side older than the field did, and a caller and a backend of
// different versions keep working together.
//
// The Go generated from this follows gRPC's conventions rather than
// slgo's own: a backend embeds UnimplementedRunnerServer, and
// RunnerClient gains a method with each new RPC.

package scriptv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_script_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backend names the implementation -- "simulator", "viewer", "slgo"
	// -- and Version is its build.  Both are for logs and bug reports; no
	// caller should change what it does based on the name.  What a
	// backend can do is in Capabilities, where it can be asked about
	// rather than guessed from a word.
	Backend      string        `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	Version      string        `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities *Capabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Ready is false when the backend is up but cannot run anything yet
	// -- a viewer not started, a grid session still logging in -- and Why
	// says which.  It is not an error: a caller may reasonably wait.
	Ready         bool   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	Why           string `protobuf:"bytes,5,opt,name=why,proto3" json:"why,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_script_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetWhy() string {
	if x != nil {
		return x.Why
	}
	return ""
}

// Capabilities is what a caller may count on.
//
// Asked for rather than assumed, because the backends differ in ways a
// test needs to know about: a simulator has no notion of a run-time
// fault reported by a region, and a viewer cannot tell one avatar's
// objects from another's.
type Capabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MaxConcurrentRuns is how many scripts this backend will run at
	// once.  One is a real answer: a viewer driven through its editor can
	// only do one thing at a time.
	MaxConcurrentRuns int32 `protobuf:"varint,1,opt,name=max_concurrent_runs,json=maxConcurrentRuns,proto3" json:"max_concurrent_runs,omitempty"`
	// CompileOnly says RunRequest.compile_only is honoured.  Where it is
	// not, asking for it is an error rather than a run.
	CompileOnly bool `protobuf:"varint,2,opt,name=compile_only,json=compileOnly,proto3" json:"compile_only,omitempty"`
	// Faults says a run-time fault is reported as a Fault rather than
	// appearing as ordinary output, or not at all.
	Faults bool `protobuf:"varint,3,opt,name=faults,proto3" json:"faults,omitempty"`
	// OutOfMemory says a fault can be told to be an out-of-memory one,
	// which is what a benchmark searching for a size limit turns on.
	OutOfMemory bool `protobuf:"varint,4,opt,name=out_of_memory,json=outOfMemory,proto3" json:"out_of_memory,omitempty"`
	// PersistentTargets says an object keeps what a script left in it
	// between runs of the same lease.  A caller that carries state from
	// one run to the next in the object needs this; without it, every run
	// starts from nothing.  slbench does not: its script says one number.
	PersistentTargets bool `protobuf:"varint,5,opt,name=persistent_targets,json=persistentTargets,proto3" json:"persistent_targets,omitempty"`
	// Agents says targets belong to named avatars, so LeaseRequest.agent
	// means something.  A simulator has no avatars and ignores it.
	Agents bool `protobuf:"varint,6,opt,name=agents,proto3" json:"agents,omitempty"`
	// Grid says this is a real Second Life session, and so that a run
	// costs money, takes region time, and can be seen by other people.
	// It is the flag a destructive test checks before doing something it
	// would not do in public.
	Grid          bool `protobuf:"varint,7,opt,name=grid,proto3" json:"grid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_script_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{2}
}

func (x *Capabilities) GetMaxConcurrentRuns() int32 {
	if x != nil {
		return x.MaxConcurrentRuns
	}
	return 0
}

func (x *Capabilities) GetCompileOnly() bool {
	if x != nil {
		return x.CompileOnly
	}
	return false
}

func (x *Capabilities) GetFaults() bool {
	if x != nil {
		return x.Faults
	}
	return false
}

func (x *Capabilities) GetOutOfMemory() bool {
	if x != nil {
		return x.OutOfMemory
	}
	return false
}

func (x *Capabilities) GetPersistentTargets() bool {
	if x != nil {
		return x.PersistentTargets
	}
	return false
}

func (x *Capabilities) GetAgents() bool {
	if x != nil {
		return x.Agents
	}
	return false
}

func (x *Capabilities) GetGrid() bool {
	if x != nil {
		return x.Grid
	}
	return false
}

type PoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolRequest) Reset() {
	*x = PoolRequest{}
	mi := &file_script_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolRequest) ProtoMessage() {}

func (x *PoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolRequest.ProtoReflect.Descriptor instead.
func (*PoolRequest) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{3}
}

type PoolResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Agents []*PoolAgent           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	// Waiting is how many callers are queued for a lease across all of
	// them.
	Waiting       int32 `protobuf:"varint,2,opt,name=waiting,proto3" json:"waiting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolResponse) Reset() {
	*x = PoolResponse{}
	mi := &file_script_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolResponse) ProtoMessage() {}

func (x *PoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolResponse.ProtoReflect.Descriptor instead.
func (*PoolResponse) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{4}
}

func (x *PoolResponse) GetAgents() []*PoolAgent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *PoolResponse) GetWaiting() int32 {
	if x != nil {
		return x.Waiting
	}
	return 0
}

// PoolAgent is one avatar, or the single anonymous holder of everything
// on a backend with no avatars.
type PoolAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Agent string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// Groups are the sets of objects a lease is granted from.  A group is
	// taken whole: handing out objects one at a time lets two callers
	// each hold some and wait for the rest, which is a deadlock where a
	// queue is merely slow.
	Groups        []*PoolGroup `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolAgent) Reset() {
	*x = PoolAgent{}
	mi := &file_script_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolAgent) ProtoMessage() {}

func (x *PoolAgent) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolAgent.ProtoReflect.Descriptor instead.
func (*PoolAgent) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{5}
}

func (x *PoolAgent) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *PoolAgent) GetGroups() []*PoolGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type PoolGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Group int32                  `protobuf:"varint,1,opt,name=group,proto3" json:"group,omitempty"`
	Size  int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// HeldBy names whoever has it, for a person wondering what else is
	// running.  Empty means free.
	HeldBy        string `protobuf:"bytes,3,opt,name=held_by,json=heldBy,proto3" json:"held_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolGroup) Reset() {
	*x = PoolGroup{}
	mi := &file_script_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolGroup) ProtoMessage() {}

func (x *PoolGroup) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolGroup.ProtoReflect.Descriptor instead.
func (*PoolGroup) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{6}
}

func (x *PoolGroup) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *PoolGroup) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PoolGroup) GetHeldBy() string {
	if x != nil {
		return x.HeldBy
	}
	return ""
}

type LeaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Targets is how many objects are wanted, and they are granted
	// together or not at all.
	//
	// Zero means one.  More than a group holds is an error rather than a
	// wait that will never end.
	Targets int32 `protobuf:"varint,1,opt,name=targets,proto3" json:"targets,omitempty"`
	// Agent asks for a particular avatar's objects.  Empty takes the
	// first free group anywhere, which is what a caller that does not
	// mind should say -- naming one is honoured exactly, including the
	// waiting, since being given another avatar would be worse than being
	// slow.
	Agent string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	// Who is the caller, for the pool listing and the logs.  A person
	// wondering what is holding the objects is better served by
	// "slbench string-concat" than by a client address.
	Who string `protobuf:"bytes,3,opt,name=who,proto3" json:"who,omitempty"`
	// Wait bounds how long to queue when everything is busy.  Zero waits
	// as long as the stream lives; a caller that would rather fail fast
	// sets it.
	WaitSeconds   int64 `protobuf:"varint,4,opt,name=wait_seconds,json=waitSeconds,proto3" json:"wait_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_script_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{7}
}

func (x *LeaseRequest) GetTargets() int32 {
	if x != nil {
		return x.Targets
	}
	return 0
}

func (x *LeaseRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *LeaseRequest) GetWho() string {
	if x != nil {
		return x.Who
	}
	return ""
}

func (x *LeaseRequest) GetWaitSeconds() int64 {
	if x != nil {
		return x.WaitSeconds
	}
	return 0
}

type LeaseEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*LeaseEvent_Granted
	//	*LeaseEvent_Queued
	Event         isLeaseEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseEvent) Reset() {
	*x = LeaseEvent{}
	mi := &file_script_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseEvent) ProtoMessage() {}

func (x *LeaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseEvent.ProtoReflect.Descriptor instead.
func (*LeaseEvent) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{8}
}

func (x *LeaseEvent) GetEvent() isLeaseEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *LeaseEvent) GetGranted() *Granted {
	if x != nil {
		if x, ok := x.Event.(*LeaseEvent_Granted); ok {
			return x.Granted
		}
	}
	return nil
}

func (x *LeaseEvent) GetQueued() *Queued {
	if x != nil {
		if x, ok := x.Event.(*LeaseEvent_Queued); ok {
			return x.Queued
		}
	}
	return nil
}

type isLeaseEvent_Event interface {
	isLeaseEvent_Event()
}

type LeaseEvent_Granted struct {
	Granted *Granted `protobuf:"bytes,1,opt,name=granted,proto3,oneof"`
}

type LeaseEvent_Queued struct {
	Queued *Queued `protobuf:"bytes,2,opt,name=queued,proto3,oneof"`
}

func (*LeaseEvent_Granted) isLeaseEvent_Event() {}

func (*LeaseEvent_Queued) isLeaseEvent_Event() {}

type Granted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Targets are what to run in, in the order they were asked for.  They
	// are valid until this stream ends and are meaningless to anybody
	// else.
	Targets []*Target `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	// Agent is whose objects these turned out to be, which a caller that
	// did not name one should say out loud: a reading is only comparable
	// with another from the same avatar.
	Agent string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	// Group is which group of the pool this is, for the same reason the
	// pool listing exists.
	Group         int32 `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Granted) Reset() {
	*x = Granted{}
	mi := &file_script_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Granted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Granted) ProtoMessage() {}

func (x *Granted) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Granted.ProtoReflect.Descriptor instead.
func (*Granted) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{9}
}

func (x *Granted) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Granted) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Granted) GetGroup() int32 {
	if x != nil {
		return x.Group
	}
	return 0
}

type Queued struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ahead is how many callers are in front.  It is a hint for a log
	// line, not a promise about order.
	Ahead         int32 `protobuf:"varint,1,opt,name=ahead,proto3" json:"ahead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queued) Reset() {
	*x = Queued{}
	mi := &file_script_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queued) ProtoMessage() {}

func (x *Queued) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queued.ProtoReflect.Descriptor instead.
func (*Queued) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{10}
}

func (x *Queued) GetAhead() int32 {
	if x != nil {
		return x.Ahead
	}
	return 0
}

// Target is somewhere a script can run.
//
// The id is opaque and belongs to the backend: a grid object's uuid, a
// viewer's slot file, a name the simulator made up.  A caller passes it
// back and does not read it.  Name is what a person would call it.
type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_script_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{11}
}

func (x *Target) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Target) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target is where to run, from a Granted on a lease held by this same
	// caller.
	//
	// Empty means anywhere: the backend takes somewhere, runs, and gives
	// it back.  That is the whole of what a one-off script needs, and it
	// saves a caller holding a lease stream to run a single script.
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// Name is what the script is called inside the object.  Reusing a
	// name replaces that script rather than adding another.  Empty lets
	// the backend choose, which is what a caller with one script and no
	// opinion wants.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Source is the LSL.
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Done is the text that means the script has finished; the run ends
	// as soon as a line contains it.
	//
	// Without one there is no way to tell a script that has finished from
	// one about to speak again, and the run can only wait out the
	// timeout.  Have the script say something distinctive at the end and
	// name it here.
	Done string `protobuf:"bytes,4,opt,name=done,proto3" json:"done,omitempty"`
	// TimeoutSeconds is how long to wait for Done.  Reaching it is not an
	// error: the lines heard so far are still sent, and Finished says the
	// sentinel was never seen.  A script that says nothing is a result
	// worth seeing rather than a failure to report.
	TimeoutSeconds int64 `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// CompileOnly installs the script without starting it, which is how
	// to get a compiler verdict without disturbing anything the object
	// holds.  Nothing runs, so no linkset data is written and no
	// measurement in progress is spoiled.
	CompileOnly bool `protobuf:"varint,6,opt,name=compile_only,json=compileOnly,proto3" json:"compile_only,omitempty"`
	// IgnoreFault keeps the run going after a fault the backend blames on
	// this script.  By default a fault ends it, because the script has
	// stopped and the sentinel is never coming.  Set this when something
	// else in the object is expected to carry on talking.
	IgnoreFault   bool `protobuf:"varint,7,opt,name=ignore_fault,json=ignoreFault,proto3" json:"ignore_fault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_script_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{12}
}

func (x *RunRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RunRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RunRequest) GetDone() string {
	if x != nil {
		return x.Done
	}
	return ""
}

func (x *RunRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *RunRequest) GetCompileOnly() bool {
	if x != nil {
		return x.CompileOnly
	}
	return false
}

func (x *RunRequest) GetIgnoreFault() bool {
	if x != nil {
		return x.IgnoreFault
	}
	return false
}

type RunEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunEvent_Compiled
	//	*RunEvent_Line
	//	*RunEvent_Fault
	//	*RunEvent_Finished
	Event         isRunEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_script_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{13}
}

func (x *RunEvent) GetEvent() isRunEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunEvent) GetCompiled() *Compiled {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Compiled); ok {
			return x.Compiled
		}
	}
	return nil
}

func (x *RunEvent) GetLine() *Line {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Line); ok {
			return x.Line
		}
	}
	return nil
}

func (x *RunEvent) GetFault() *Fault {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Fault); ok {
			return x.Fault
		}
	}
	return nil
}

func (x *RunEvent) GetFinished() *Finished {
	if x != nil {
		if x, ok := x.Event.(*RunEvent_Finished); ok {
			return x.Finished
		}
	}
	return nil
}

type isRunEvent_Event interface {
	isRunEvent_Event()
}

type RunEvent_Compiled struct {
	// Compiled comes first and exactly once.  A script that would not
	// compile is followed by Finished and nothing else.
	Compiled *Compiled `protobuf:"bytes,1,opt,name=compiled,proto3,oneof"`
}

type RunEvent_Line struct {
	// Line is one thing the object said, as it is heard.
	Line *Line `protobuf:"bytes,2,opt,name=line,proto3,oneof"`
}

type RunEvent_Fault struct {
	// Fault is a run-time error the backend blames on this script.
	Fault *Fault `protobuf:"bytes,3,opt,name=fault,proto3,oneof"`
}

type RunEvent_Finished struct {
	// Finished comes last and exactly once, whatever happened.
	Finished *Finished `protobuf:"bytes,4,opt,name=finished,proto3,oneof"`
}

func (*RunEvent_Compiled) isRunEvent_Event() {}

func (*RunEvent_Line) isRunEvent_Event() {}

func (*RunEvent_Fault) isRunEvent_Event() {}

func (*RunEvent_Finished) isRunEvent_Event() {}

type Compiled struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Errors is what the compiler complained about.  There is usually at
	// most one: a compiler reports the first error and stops.
	Errors []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Item is the script's id inside the object where a backend has such
	// a thing, which is not the id of whatever it was copied from.
	Item          string `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compiled) Reset() {
	*x = Compiled{}
	mi := &file_script_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compiled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compiled) ProtoMessage() {}

func (x *Compiled) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compiled.ProtoReflect.Descriptor instead.
func (*Compiled) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{14}
}

func (x *Compiled) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Compiled) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *Compiled) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

type Line struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// AtUnixNanos is when it was heard.
	AtUnixNanos int64 `protobuf:"varint,2,opt,name=at_unix_nanos,json=atUnixNanos,proto3" json:"at_unix_nanos,omitempty"`
	// Debug marks the channel a region comments on scripts on, as against
	// the script speaking.  A caller printing a transcript for a person
	// leaves these out; one diagnosing a failure wants them.
	Debug bool `protobuf:"varint,3,opt,name=debug,proto3" json:"debug,omitempty"`
	// From is the name of whatever spoke and Source is its opaque id.
	// Both are worth having when several objects are talking at once.
	From          string `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	Source        string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_script_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{15}
}

func (x *Line) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Line) GetAtUnixNanos() int64 {
	if x != nil {
		return x.AtUnixNanos
	}
	return 0
}

func (x *Line) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *Line) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Line) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Fault struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Script is which script was blamed, which need not be the one just
	// sent -- an object may hold others.
	Script string `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	// Reason is what the backend said, in its own words.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// OutOfMemory is the one kind worth telling apart, since a benchmark
	// searching for a size limit treats it as the answer rather than as a
	// failure.  Backends that cannot tell leave it false and say so in
	// Capabilities.
	OutOfMemory   bool `protobuf:"varint,3,opt,name=out_of_memory,json=outOfMemory,proto3" json:"out_of_memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fault) Reset() {
	*x = Fault{}
	mi := &file_script_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fault) ProtoMessage() {}

func (x *Fault) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fault.ProtoReflect.Descriptor instead.
func (*Fault) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{16}
}

func (x *Fault) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *Fault) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Fault) GetOutOfMemory() bool {
	if x != nil {
		return x.OutOfMemory
	}
	return false
}

type Finished struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sentinel says Done was seen.  False after a timeout, a fault that
	// ended the run, or a script that would not compile.
	Sentinel bool `protobuf:"varint,1,opt,name=sentinel,proto3" json:"sentinel,omitempty"`
	// ElapsedMillis is how long the run took, measured by the backend --
	// the only side that can leave out its own queueing.
	ElapsedMillis int64 `protobuf:"varint,2,opt,name=elapsed_millis,json=elapsedMillis,proto3" json:"elapsed_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finished) Reset() {
	*x = Finished{}
	mi := &file_script_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finished) ProtoMessage() {}

func (x *Finished) ProtoReflect() protoreflect.Message {
	mi := &file_script_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finished.ProtoReflect.Descriptor instead.
func (*Finished) Descriptor() ([]byte, []int) {
	return file_script_proto_rawDescGZIP(), []int{17}
}

func (x *Finished) GetSentinel() bool {
	if x != nil {
		return x.Sentinel
	}
	return false
}

func (x *Finished) GetElapsedMillis() int64 {
	if x != nil {
		return x.ElapsedMillis
	}
	return 0
}

var File_script_proto protoreflect.FileDescriptor

const file_script_proto_rawDesc = "" +
	"\n" +
	"\fscript.proto\x12\tscript.v1\"\x0f\n" +
	"\rHealthRequest\"\xa9\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12;\n" +
	"\fcapabilities\x18\x03 \x01(\v2\x17.script.v1.CapabilitiesR\fcapabilities\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12\x10\n" +
	"\x03why\x18\x05 \x01(\tR\x03why\"\xf8\x01\n" +
	"\fCapabilities\x12.\n" +
	"\x13max_concurrent_runs\x18\x01 \x01(\x05R\x11maxConcurrentRuns\x12!\n" +
	"\fcompile_only\x18\x02 \x01(\bR\vcompileOnly\x12\x16\n" +
	"\x06faults\x18\x03 \x01(\bR\x06faults\x12\"\n" +
	"\rout_of_memory\x18\x04 \x01(\bR\voutOfMemory\x12-\n" +
	"\x12persistent_targets\x18\x05 \x01(\bR\x11persistentTargets\x12\x16\n" +
	"\x06agents\x18\x06 \x01(\bR\x06agents\x12\x12\n" +
	"\x04grid\x18\a \x01(\bR\x04grid\"\r\n" +
	"\vPoolRequest\"V\n" +
	"\fPoolResponse\x12,\n" +
	"\x06agents\x18\x01 \x03(\v2\x14.script.v1.PoolAgentR\x06agents\x12\x18\n" +
	"\awaiting\x18\x02 \x01(\x05R\awaiting\"O\n" +
	"\tPoolAgent\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12,\n" +
	"\x06groups\x18\x02 \x03(\v2\x14.script.v1.PoolGroupR\x06groups\"N\n" +
	"\tPoolGroup\x12\x14\n" +
	"\x05group\x18\x01 \x01(\x05R\x05group\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x17\n" +
	"\aheld_by\x18\x03 \x01(\tR\x06heldBy\"s\n" +
	"\fLeaseRequest\x12\x18\n" +
	"\atargets\x18\x01 \x01(\x05R\atargets\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x10\n" +
	"\x03who\x18\x03 \x01(\tR\x03who\x12!\n" +
	"\fwait_seconds\x18\x04 \x01(\x03R\vwaitSeconds\"r\n" +
	"\n" +
	"LeaseEvent\x12.\n" +
	"\agranted\x18\x01 \x01(\v2\x12.script.v1.GrantedH\x00R\agranted\x12+\n" +
	"\x06queued\x18\x02 \x01(\v2\x11.script.v1.QueuedH\x00R\x06queuedB\a\n" +
	"\x05event\"b\n" +
	"\aGranted\x12+\n" +
	"\atargets\x18\x01 \x03(\v2\x11.script.v1.TargetR\atargets\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x14\n" +
	"\x05group\x18\x03 \x01(\x05R\x05group\"\x1e\n" +
	"\x06Queued\x12\x14\n" +
	"\x05ahead\x18\x01 \x01(\x05R\x05ahead\",\n" +
	"\x06Target\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xd3\x01\n" +
	"\n" +
	"RunRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x12\n" +
	"\x04done\x18\x04 \x01(\tR\x04done\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\x12!\n" +
	"\fcompile_only\x18\x06 \x01(\bR\vcompileOnly\x12!\n" +
	"\fignore_fault\x18\a \x01(\bR\vignoreFault\"\xca\x01\n" +
	"\bRunEvent\x121\n" +
	"\bcompiled\x18\x01 \x01(\v2\x13.script.v1.CompiledH\x00R\bcompiled\x12%\n" +
	"\x04line\x18\x02 \x01(\v2\x0f.script.v1.LineH\x00R\x04line\x12(\n" +
	"\x05fault\x18\x03 \x01(\v2\x10.script.v1.FaultH\x00R\x05fault\x121\n" +
	"\bfinished\x18\x04 \x01(\v2\x13.script.v1.FinishedH\x00R\bfinishedB\a\n" +
	"\x05event\"F\n" +
	"\bCompiled\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x12\n" +
	"\x04item\x18\x03 \x01(\tR\x04item\"\x80\x01\n" +
	"\x04Line\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\"\n" +
	"\rat_unix_nanos\x18\x02 \x01(\x03R\vatUnixNanos\x12\x14\n" +
	"\x05debug\x18\x03 \x01(\bR\x05debug\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"[\n" +
	"\x05Fault\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\"\n" +
	"\rout_of_memory\x18\x03 \x01(\bR\voutOfMemory\"M\n" +
	"\bFinished\x12\x1a\n" +
	"\bsentinel\x18\x01 \x01(\bR\bsentinel\x12%\n" +
	"\x0eelapsed_millis\x18\x02 \x01(\x03R\relapsedMillis2\xf0\x01\n" +
	"\x06Runner\x12=\n" +
	"\x06Health\x12\x18.script.v1.HealthRequest\x1a\x19.script.v1.HealthResponse\x127\n" +
	"\x04Pool\x12\x16.script.v1.PoolRequest\x1a\x17.script.v1.PoolResponse\x129\n" +
	"\x05Lease\x12\x17.script.v1.LeaseRequest\x1a\x15.script.v1.LeaseEvent0\x01\x123\n" +
	"\x03Run\x12\x15.script.v1.RunRequest\x1a\x13.script.v1.RunEvent0\x01B/Z-github.com/quark-idlemind/slgo/proto/scriptv1b\x06proto3"

var (
	file_script_proto_rawDescOnce sync.Once
	file_script_proto_rawDescData []byte
)

func file_script_proto_rawDescGZIP() []byte {
	file_script_proto_rawDescOnce.Do(func() {
		file_script_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_script_proto_rawDesc), len(file_script_proto_rawDesc)))
	})
	return file_script_proto_rawDescData
}

var file_script_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_script_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: script.v1.HealthRequest
	(*HealthResponse)(nil), // 1: script.v1.HealthResponse
	(*Capabilities)(nil),   // 2: script.v1.Capabilities
	(*PoolRequest)(nil),    // 3: script.v1.PoolRequest
	(*PoolResponse)(nil),   // 4: script.v1.PoolResponse
	(*PoolAgent)(nil),      // 5: script.v1.PoolAgent
	(*PoolGroup)(nil),      // 6: script.v1.PoolGroup
	(*LeaseRequest)(nil),   // 7: script.v1.LeaseRequest
	(*LeaseEvent)(nil),     // 8: script.v1.LeaseEvent
	(*Granted)(nil),        // 9: script.v1.Granted
	(*Queued)(nil),         // 10: script.v1.Queued
	(*Target)(nil),         // 11: script.v1.Target
	(*RunRequest)(nil),     // 12: script.v1.RunRequest
	(*RunEvent)(nil),       // 13: script.v1.RunEvent
	(*Compiled)(nil),       // 14: script.v1.Compiled
	(*Line)(nil),           // 15: script.v1.Line
	(*Fault)(nil),          // 16: script.v1.Fault
	(*Finished)(nil),       // 17: script.v1.Finished
}
var file_script_proto_depIdxs = []int32{
	2,  // 0: script.v1.HealthResponse.capabilities:type_name -> script.v1.Capabilities
	5,  // 1: script.v1.PoolResponse.agents:type_name -> script.v1.PoolAgent
	6,  // 2: script.v1.PoolAgent.groups:type_name -> script.v1.PoolGroup
	9,  // 3: script.v1.LeaseEvent.granted:type_name -> script.v1.Granted
	10, // 4: script.v1.LeaseEvent.queued:type_name -> script.v1.Queued
	11, // 5: script.v1.Granted.targets:type_name -> script.v1.Target
	14, // 6: script.v1.RunEvent.compiled:type_name -> script.v1.Compiled
	15, // 7: script.v1.RunEvent.line:type_name -> script.v1.Line
	16, // 8: script.v1.RunEvent.fault:type_name -> script.v1.Fault
	17, // 9: script.v1.RunEvent.finished:type_name -> script.v1.Finished
	0,  // 10: script.v1.Runner.Health:input_type -> script.v1.HealthRequest
	3,  // 11: script.v1.Runner.Pool:input_type -> script.v1.PoolRequest
	7,  // 12: script.v1.Runner.Lease:input_type -> script.v1.LeaseRequest
	12, // 13: script.v1.Runner.Run:input_type -> script.v1.RunRequest
	1,  // 14: script.v1.Runner.Health:output_type -> script.v1.HealthResponse
	4,  // 15: script.v1.Runner.Pool:output_type -> script.v1.PoolResponse
	8,  // 16: script.v1.Runner.Lease:output_type -> script.v1.LeaseEvent
	13, // 17: script.v1.Runner.Run:output_type -> script.v1.RunEvent
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_script_proto_init() }
func file_script_proto_init() {
	if File_script_proto != nil {
		return
	}
	file_script_proto_msgTypes[8].OneofWrappers = []any{
		(*LeaseEvent_Granted)(nil),
		(*LeaseEvent_Queued)(nil),
	}
	file_script_proto_msgTypes[13].OneofWrappers = []any{
		(*RunEvent_Compiled)(nil),
		(*RunEvent_Line)(nil),
		(*RunEvent_Fault)(nil),
		(*RunEvent_Finished)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_script_proto_rawDesc), len(file_script_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_script_proto_goTypes,
		DependencyIndexes: file_script_proto_depIdxs,
		MessageInfos:      file_script_proto_msgTypes,
	}.Build()
	File_script_proto = out.File
	file_script_proto_goTypes = nil
	file_script_proto_depIdxs = nil
}
