// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: script.proto

// Package script.v1 is how a program that wants LSL run asks something
// else to run it.
//
// The programs are slrun and slbench: they write a script, put it
// somewhere it can run, watch what it says, and want to know whether it
// compiled, whether it faulted and whether it got to the end.  None of
// that is particular to Second Life.  The same script can be run by the
// eLSL simulator with no grid at all, or by a viewer driven from
// outside, or by a client holding a real grid session -- and the caller
// should not have to be written three times to say so.
//
// So this is the seam.  A backend is anything that can be handed a
// script and made to answer these questions, and it lives wherever it
// likes: in this repository, beside the simulator, or beside a viewer.
//
// # What a backend owns and what a caller owns
//
// The backend owns everything that would break if the caller restarted:
// the grid session or the viewer, the objects a script runs in, which
// of them are busy, and the queue for them when they all are.  The
// caller owns the script and what its output means.
//
// That division is why a lease is a stream rather than a pair of calls.
// A caller that dies mid-benchmark must not leave objects held forever,
// and no timeout is a good answer to that: too short and a long run
// loses its objects, too long and a crash blocks the pool.  A stream
// answers exactly: the objects are held while the caller is there.
//
// # What is deliberately not here
//
// Rezzing, linking, texturing, inventory.  A script runs inside an
// object and the backend supplies one; how it came to exist is the
// backend's business.  The simulator has no prims, the viewer has slot
// files, a grid client rezzes and wears things, and a caller that had
// to know which would be back to being written three times.
//
// Nor is there anything for reading state back out of an object.  A
// benchmark that wants a number from the last run has the script say
// it, which works everywhere; anything else would be an interface to
// linkset data, which two of the three backends do not have.

package scriptv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runner_Health_FullMethodName = "/script.v1.Runner/Health"
	Runner_Pool_FullMethodName   = "/script.v1.Runner/Pool"
	Runner_Lease_FullMethodName  = "/script.v1.Runner/Lease"
	Runner_Run_FullMethodName    = "/script.v1.Runner/Run"
)

// RunnerClient is the client API for Runner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Runner runs LSL and says what happened.
type RunnerClient interface {
	// Health is what this backend is and what it can do.  It is also the
	// liveness check: a backend that answers is up.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Pool is what there is to run in, and what is busy.  It is for a
	// person asking why their benchmark is queued, and for a caller
	// deciding how many runs to start at once.
	Pool(ctx context.Context, in *PoolRequest, opts ...grpc.CallOption) (*PoolResponse, error)
	// Lease takes somewhere to run and holds it until the stream ends.
	//
	// The objects are the caller's alone until then, which is what a
	// measurement needs: a benchmark leaves its base reading inside the
	// object between runs, and a second caller in the same object would
	// read somebody else's numbers.
	//
	// Ending the stream gives them back.  So does dying, which is the
	// point -- there is no Release to forget to call, and no lease timer
	// to tune between "a long run loses its objects" and "a crash blocks
	// the pool".
	//
	// The first event is Granted or Queued; Queued may be followed by
	// Granted when a turn comes up.
	Lease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaseEvent], error)
	// Run runs one script and streams back what it said.
	//
	// Streaming rather than returning a transcript because a run can last
	// minutes and a person watching wants the lines as they arrive.  A
	// caller that only wants the whole thing collects the stream.
	//
	// Cancelling the call stops the run.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
}

type runnerClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerClient(cc grpc.ClientConnInterface) RunnerClient {
	return &runnerClient{cc}
}

func (c *runnerClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Runner_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) Pool(ctx context.Context, in *PoolRequest, opts ...grpc.CallOption) (*PoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolResponse)
	err := c.cc.Invoke(ctx, Runner_Pool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) Lease(ctx context.Context, in *LeaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaseEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runner_ServiceDesc.Streams[0], Runner_Lease_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LeaseRequest, LeaseEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_LeaseClient = grpc.ServerStreamingClient[LeaseEvent]

func (c *runnerClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runner_ServiceDesc.Streams[1], Runner_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_RunClient = grpc.ServerStreamingClient[RunEvent]

// RunnerServer is the server API for Runner service.
// All implementations must embed UnimplementedRunnerServer
// for forward compatibility.
//
// Runner runs LSL and says what happened.
type RunnerServer interface {
	// Health is what this backend is and what it can do.  It is also the
	// liveness check: a backend that answers is up.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Pool is what there is to run in, and what is busy.  It is for a
	// person asking why their benchmark is queued, and for a caller
	// deciding how many runs to start at once.
	Pool(context.Context, *PoolRequest) (*PoolResponse, error)
	// Lease takes somewhere to run and holds it until the stream ends.
	//
	// The objects are the caller's alone until then, which is what a
	// measurement needs: a benchmark leaves its base reading inside the
	// object between runs, and a second caller in the same object would
	// read somebody else's numbers.
	//
	// Ending the stream gives them back.  So does dying, which is the
	// point -- there is no Release to forget to call, and no lease timer
	// to tune between "a long run loses its objects" and "a crash blocks
	// the pool".
	//
	// The first event is Granted or Queued; Queued may be followed by
	// Granted when a turn comes up.
	Lease(*LeaseRequest, grpc.ServerStreamingServer[LeaseEvent]) error
	// Run runs one script and streams back what it said.
	//
	// Streaming rather than returning a transcript because a run can last
	// minutes and a person watching wants the lines as they arrive.  A
	// caller that only wants the whole thing collects the stream.
	//
	// Cancelling the call stops the run.
	Run(*RunRequest, grpc.ServerStreamingServer[RunEvent]) error
	mustEmbedUnimplementedRunnerServer()
}

// UnimplementedRunnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerServer struct{}

func (UnimplementedRunnerServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRunnerServer) Pool(context.Context, *PoolRequest) (*PoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pool not implemented")
}
func (UnimplementedRunnerServer) Lease(*LeaseRequest, grpc.ServerStreamingServer[LeaseEvent]) error {
	return status.Error(codes.Unimplemented, "method Lease not implemented")
}
func (UnimplementedRunnerServer) Run(*RunRequest, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedRunnerServer) mustEmbedUnimplementedRunnerServer() {}
func (UnimplementedRunnerServer) testEmbeddedByValue()                {}

// UnsafeRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServer will
// result in compilation errors.
type UnsafeRunnerServer interface {
	mustEmbedUnimplementedRunnerServer()
}

func RegisterRunnerServer(s grpc.ServiceRegistrar, srv RunnerServer) {
	// If the following call panics, it indicates UnimplementedRunnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runner_ServiceDesc, srv)
}

func _Runner_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_Pool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).Pool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_Pool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).Pool(ctx, req.(*PoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_Lease_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LeaseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServer).Lease(m, &grpc.GenericServerStream[LeaseRequest, LeaseEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_LeaseServer = grpc.ServerStreamingServer[LeaseEvent]

func _Runner_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServer).Run(m, &grpc.GenericServerStream[RunRequest, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runner_RunServer = grpc.ServerStreamingServer[RunEvent]

// Runner_ServiceDesc is the grpc.ServiceDesc for Runner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "script.v1.Runner",
	HandlerType: (*RunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Runner_Health_Handler,
		},
		{
			MethodName: "Pool",
			Handler:    _Runner_Pool_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Lease",
			Handler:       _Runner_Lease_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Run",
			Handler:       _Runner_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "script.proto",
}
