package sl

import (
	"math"
	"testing"

	"github.com/quark-idlemind/slgo/msg"
)

// TestShapeNamesAreTwoCurves: every named shape has to pack to a pair
// the grid knows and unpack back to the name it started as, or a prim
// rezzed from JSON is silently the wrong kind.
func TestShapeNamesAreTwoCurves(t *testing.T) {
	for _, name := range ShapeNames {
		s := DefaultShape()
		s.Type = name
		p, err := s.Pack()
		if err != nil {
			t.Errorf("%s: %v", name, err)
			continue
		}
		if got := UnpackShape(p).Type; got != name {
			t.Errorf("%s packed and unpacked as %q", name, got)
		}
	}
	if _, err := (Shape{Type: "dodecahedron"}).Pack(); err == nil {
		t.Error("a shape nobody has heard of packed anyway")
	}
}

// TestTheDefaultBoxPacksAsTheViewerWouldPackIt.  These are the numbers
// from LLVolumeMessage, and getting the two inverted fields backwards
// makes a prim that is inside out rather than one that fails.
func TestTheDefaultBoxPacksAsTheViewerWouldPackIt(t *testing.T) {
	p, err := DefaultShape().Pack()
	if err != nil {
		t.Fatal(err)
	}
	want := msg.PrimShape{
		ProfileCurve: 0x01, // square
		PathCurve:    0x10, // line
		ProfileEnd:   0,    // 50000 - 50000: a whole profile
		PathEnd:      0,    // likewise
		PathScaleX:   100,  // 200 - 100: full size
		PathScaleY:   100,
	}
	if p != want {
		t.Errorf("a default box packs as\n %+v\nwant\n %+v", p, want)
	}
}

// TestEveryFieldSurvivesTheRoundTrip, to within the quantum it is
// stored in.  A field that packs but does not unpack is a prim that
// changes shape when it is described and rebuilt.
func TestEveryFieldSurvivesTheRoundTrip(t *testing.T) {
	s := Shape{
		Type: "torus", HoleShape: HoleSquare,
		CutBegin: 0.125, CutEnd: 0.75,
		Hollow:     0.5,
		TwistBegin: -0.25, TwistEnd: 0.5,
		TopSizeX: 0.4, TopSizeY: 1.6,
		TopShearX: -0.3, TopShearY: 0.2,
		AdvancedCutBegin: 0.1, AdvancedCutEnd: 0.9,
		TaperX: -0.5, TaperY: 0.25,
		Revolutions: 3.0, RadiusOffset: 0.6, Skew: -0.4,
	}
	p, err := s.Pack()
	if err != nil {
		t.Fatal(err)
	}
	got := UnpackShape(p)

	for _, c := range []struct {
		what     string
		want, is float32
		tol      float64
	}{
		{"cut begin", s.CutBegin, got.CutBegin, cutQuantum},
		{"cut end", s.CutEnd, got.CutEnd, cutQuantum},
		{"hollow", s.Hollow, got.Hollow, hollowQuantum},
		{"twist begin", s.TwistBegin, got.TwistBegin, scaleQuantum},
		{"twist end", s.TwistEnd, got.TwistEnd, scaleQuantum},
		{"top size x", s.TopSizeX, got.TopSizeX, scaleQuantum},
		{"top size y", s.TopSizeY, got.TopSizeY, scaleQuantum},
		{"top shear x", s.TopShearX, got.TopShearX, shearQuantum},
		{"top shear y", s.TopShearY, got.TopShearY, shearQuantum},
		{"advanced cut begin", s.AdvancedCutBegin, got.AdvancedCutBegin, cutQuantum},
		{"advanced cut end", s.AdvancedCutEnd, got.AdvancedCutEnd, cutQuantum},
		{"taper x", s.TaperX, got.TaperX, taperQuantum},
		{"taper y", s.TaperY, got.TaperY, taperQuantum},
		{"revolutions", s.Revolutions, got.Revolutions, revQuantum},
		{"radius offset", s.RadiusOffset, got.RadiusOffset, scaleQuantum},
		{"skew", s.Skew, got.Skew, scaleQuantum},
	} {
		if d := math.Abs(float64(c.want - c.is)); d > c.tol {
			t.Errorf("%s: %v came back %v, %v off and the quantum is %v",
				c.what, c.want, c.is, d, c.tol)
		}
	}
	if got.Type != "torus" || got.HoleShape != HoleSquare {
		t.Errorf("torus with a square hole came back as %q with hole %#x", got.Type, got.HoleShape)
	}
}

// TestTheCutSwapsWithThePath.  A prim swept along a line is cut by its
// profile and one swept round a circle by its path, which is why LSL
// calls a sphere's cut a dimple.  Getting it wrong cuts the wrong axis
// and looks like the numbers were ignored.
func TestTheCutSwapsWithThePath(t *testing.T) {
	line := Shape{Type: "box", CutBegin: 0.25, CutEnd: 0.75, TopSizeX: 1, TopSizeY: 1, Revolutions: 1}
	p, err := line.Pack()
	if err != nil {
		t.Fatal(err)
	}
	if p.ProfileBegin == 0 {
		t.Error("a box's cut did not reach the profile")
	}
	if p.PathBegin != 0 || p.PathEnd != 0 {
		t.Errorf("a box's path was cut: begin %d end %d", p.PathBegin, p.PathEnd)
	}

	round := Shape{Type: "sphere", CutBegin: 0.25, CutEnd: 0.75, TopSizeX: 1, TopSizeY: 1, Revolutions: 1}
	p, err = round.Pack()
	if err != nil {
		t.Fatal(err)
	}
	if p.PathBegin == 0 {
		t.Error("a sphere's cut did not reach the path")
	}
}

// facesCase is one prim the grid was asked about: the shape the store
// decoded from its update, and what llGetNumberOfSides answered.
type facesCase struct {
	shape Shape
	sides int
}

// TestFacesMatchWhatTheGridCounted: 340 shapes -- every one of the
// seven kinds across the cut, hollow and hole combinations -- were set
// on a prim and counted with llGetNumberOfSides on 2026-10-01, each
// shape read back from the update the simulator sent.  A second run
// the same day, measuredBentFaces, added twist, taper, skew, radius
// offset, revolutions, hole size and shear on the torus, tube and ring,
// twist on the sphere, and twist, top size and shear on the three line
// shapes.  The port of the viewer's face rule has to give the same
// number for every one.
// Why: doc/objects.md#how-many-faces-a-prim-has
func TestFacesMatchWhatTheGridCounted(t *testing.T) {
	for _, c := range append(measuredFaces, measuredBentFaces...) {
		got, ok := c.shape.Faces()
		if !ok || got != c.sides {
			t.Errorf("%+v: Faces() = %d, %v; the grid counted %d", c.shape, got, ok, c.sides)
		}
	}
}

// TestFacesAreNotGuessed: a shape of a kind the curve tables do not
// name has no count to give, nor does a cut that leaves nothing.
func TestFacesAreNotGuessed(t *testing.T) {
	if n, ok := (Shape{}).Faces(); ok {
		t.Errorf("a shape with no kind has %d faces", n)
	}
	s := DefaultShape()
	s.CutBegin, s.CutEnd = 0.5, 0.505
	if n, ok := s.Faces(); ok {
		t.Errorf("a cut of a two-hundredth left %d faces", n)
	}
}

var measuredFaces = []facesCase{
	{Shape{Type: "box", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutBegin: 0.25, CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", CutEnd: 0.75, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", CutEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutBegin: 0.5, CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutBegin: 0.1, CutEnd: 0.2, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "box", CutBegin: 0.6, CutEnd: 0.65, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "box", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 9},
	{Shape{Type: "box", CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", HoleShape: 0x10, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", HoleShape: 0x10, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", HoleShape: 0x10, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", HoleShape: 0x10, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 9},
	{Shape{Type: "box", HoleShape: 0x10, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", HoleShape: 0x10, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", HoleShape: 0x10, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", HoleShape: 0x10, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", HoleShape: 0x20, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", HoleShape: 0x20, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", HoleShape: 0x20, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", HoleShape: 0x20, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 9},
	{Shape{Type: "box", HoleShape: 0x20, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", HoleShape: 0x20, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", HoleShape: 0x20, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", HoleShape: 0x20, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", HoleShape: 0x30, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", HoleShape: 0x30, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", HoleShape: 0x30, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", HoleShape: 0x30, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 9},
	{Shape{Type: "box", HoleShape: 0x30, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", HoleShape: 0x30, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", HoleShape: 0x30, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", HoleShape: 0x30, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutEnd: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutBegin: 0.2, CutEnd: 0.8, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", CutEnd: 1, Hollow: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 9},
	{Shape{Type: "cylinder", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "cylinder", CutBegin: 0.25, CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutEnd: 0.75, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutBegin: 0.5, CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutBegin: 0.1, CutEnd: 0.2, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutBegin: 0.6, CutEnd: 0.65, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "cylinder", CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x10, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "cylinder", HoleShape: 0x10, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x10, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x10, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x10, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x10, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x10, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x10, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x20, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "cylinder", HoleShape: 0x20, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x20, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x20, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x20, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x20, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x20, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x20, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x30, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "cylinder", HoleShape: 0x30, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x30, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x30, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x30, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x30, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x30, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", HoleShape: 0x30, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "cylinder", CutEnd: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "cylinder", CutBegin: 0.2, CutEnd: 0.8, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutEnd: 1, Hollow: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "cylinder", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "prism", CutBegin: 0.25, CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutEnd: 0.75, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutBegin: 0.5, CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutBegin: 0.1, CutEnd: 0.2, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "prism", CutBegin: 0.6, CutEnd: 0.65, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "prism", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", HoleShape: 0x10, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", HoleShape: 0x10, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", HoleShape: 0x10, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", HoleShape: 0x10, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", HoleShape: 0x10, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", HoleShape: 0x10, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", HoleShape: 0x10, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", HoleShape: 0x10, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", HoleShape: 0x20, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", HoleShape: 0x20, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", HoleShape: 0x20, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", HoleShape: 0x20, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", HoleShape: 0x20, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", HoleShape: 0x20, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", HoleShape: 0x20, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", HoleShape: 0x20, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", HoleShape: 0x30, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", HoleShape: 0x30, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", HoleShape: 0x30, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", HoleShape: 0x30, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "prism", HoleShape: 0x30, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", HoleShape: 0x30, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", HoleShape: 0x30, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", HoleShape: 0x30, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutEnd: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "prism", CutBegin: 0.2, CutEnd: 0.8, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutEnd: 1, Hollow: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "sphere", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 1},
	{Shape{Type: "sphere", CutBegin: 0.25, CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutEnd: 0.75, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutBegin: 0.5, CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutBegin: 0.1, CutEnd: 0.2, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutBegin: 0.6, CutEnd: 0.65, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "sphere", CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x10, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "sphere", HoleShape: 0x10, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x10, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x10, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x10, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x10, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x10, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x10, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x20, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "sphere", HoleShape: 0x20, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x20, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x20, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x20, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x20, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x20, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x20, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x30, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "sphere", HoleShape: 0x30, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x30, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x30, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x30, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x30, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x30, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", HoleShape: 0x30, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "sphere", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 0.8, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "sphere", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 0.8, Revolutions: 1}, 4},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "sphere", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "sphere", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 4},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 1},
	{Shape{Type: "torus", CutBegin: 0.25, CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 0.75, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.5, CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.1, CutEnd: 0.2, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.6, CutEnd: 0.65, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 2},
	{Shape{Type: "torus", CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x10, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 2},
	{Shape{Type: "torus", HoleShape: 0x10, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x10, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x10, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x10, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x10, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x10, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x10, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x20, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 2},
	{Shape{Type: "torus", HoleShape: 0x20, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x20, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x20, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x20, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x20, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x20, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x20, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x30, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 2},
	{Shape{Type: "torus", HoleShape: 0x30, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x30, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x30, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x30, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x30, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x30, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", HoleShape: 0x30, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "tube", CutBegin: 0.25, CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 0.75, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.5, CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.1, CutEnd: 0.2, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.6, CutEnd: 0.65, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "tube", CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x10, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "tube", HoleShape: 0x10, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x10, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x10, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x10, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x10, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x10, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x10, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x20, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "tube", HoleShape: 0x20, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x20, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x20, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x20, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x20, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x20, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x20, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x30, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "tube", HoleShape: 0x30, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x30, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x30, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x30, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x30, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x30, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", HoleShape: 0x30, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 9},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 8},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 9},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 8},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 9},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "ring", CutBegin: 0.25, CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 0.75, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.5, CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.1, CutEnd: 0.2, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.6, CutEnd: 0.65, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "ring", CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x10, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "ring", HoleShape: 0x10, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x10, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x10, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x10, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x10, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x10, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x10, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x20, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "ring", HoleShape: 0x20, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x20, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x20, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x20, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x20, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x20, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x20, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x30, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "ring", HoleShape: 0x30, CutBegin: 0.25, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x30, CutEnd: 0.75, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x30, CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x30, CutEnd: 0.5, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x30, CutBegin: 0.5, CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x30, CutBegin: 0.1, CutEnd: 0.2, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", HoleShape: 0x30, CutBegin: 0.6, CutEnd: 0.65, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 7},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 0.8, Revolutions: 1}, 8},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 7},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 8},
}

// measuredBentFaces is the second run: 366 shapes, 342 of them distinct
// once read back, each alone and crossed with a path cut, hollow and a
// profile cut.
var measuredBentFaces = []facesCase{
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 1},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 2},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "torus", CutEnd: 1, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutEnd: 1, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "torus", CutEnd: 1, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 1},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 2},
	{Shape{Type: "torus", CutEnd: 1, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutEnd: 1, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: 0.5, Revolutions: 1}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperY: -0.5, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperY: -0.5, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperY: -0.5, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperY: -0.5, Revolutions: 1}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.02, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.02, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.02, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: 0.02, Revolutions: 1}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: 0.19999999}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: 0.19999999}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: 0.19999999}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, Skew: 0.19999999}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: -0.19999999}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: -0.19999999}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: -0.19999999}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, Skew: -0.19999999}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.0049999, Skew: 0.66999996}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.5}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.5}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.5}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, RadiusOffset: 0.5}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: -0.5}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: -0.5}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: -0.5}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, RadiusOffset: -0.5}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.02}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.02}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.02}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, RadiusOffset: 0.02}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 3.5049999, Skew: 0.78}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 3.5049999, Skew: 0.78}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 3.5049999, Skew: 0.78}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 3.5049999, Skew: 0.78}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 1},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 2},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 1},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 2},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutEnd: 1, Revolutions: 1}, 1},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutEnd: 1, Revolutions: 1}, 2},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 4},
	{Shape{Type: "torus", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: 0.5, Revolutions: 1}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 5},
	{Shape{Type: "torus", CutEnd: 1, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 4},
	{Shape{Type: "torus", CutEnd: 1, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.0049999, Skew: 0.66999996}, 5},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 3},
	{Shape{Type: "torus", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 3},
	{Shape{Type: "torus", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 4},
	{Shape{Type: "torus", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 5},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 8},
	{Shape{Type: "tube", CutEnd: 1, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutEnd: 1, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 8},
	{Shape{Type: "tube", CutEnd: 1, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "tube", CutEnd: 1, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutEnd: 1, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: 0.5, Revolutions: 1}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperY: -0.5, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperY: -0.5, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperY: -0.5, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperY: -0.5, Revolutions: 1}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.02, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.02, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.02, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: 0.02, Revolutions: 1}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: 0.19999999}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: 0.19999999}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: 0.19999999}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, Skew: 0.19999999}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: -0.19999999}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: -0.19999999}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: -0.19999999}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, Skew: -0.19999999}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.0049999, Skew: 0.66999996}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.5}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.5}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.5}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, RadiusOffset: 0.5}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: -0.5}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: -0.5}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: -0.5}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, RadiusOffset: -0.5}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.02}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.02}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.02}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, RadiusOffset: 0.02}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 3.5049999, Skew: 0.78}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 3.5049999, Skew: 0.78}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 3.5049999, Skew: 0.78}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 3.5049999, Skew: 0.78}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 7},
	{Shape{Type: "tube", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: 0.5, Revolutions: 1}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 8},
	{Shape{Type: "tube", CutEnd: 1, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 7},
	{Shape{Type: "tube", CutEnd: 1, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.0049999, Skew: 0.66999996}, 8},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 6},
	{Shape{Type: "tube", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 6},
	{Shape{Type: "tube", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 7},
	{Shape{Type: "tube", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 8},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 7},
	{Shape{Type: "ring", CutEnd: 1, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutEnd: 1, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 7},
	{Shape{Type: "ring", CutEnd: 1, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "ring", CutEnd: 1, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutEnd: 1, TwistEnd: 0.02, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: 0.5, Revolutions: 1}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperY: -0.5, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperY: -0.5, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperY: -0.5, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperY: -0.5, Revolutions: 1}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.02, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.02, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.02, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: 0.02, Revolutions: 1}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: 0.19999999}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: 0.19999999}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: 0.19999999}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, Skew: 0.19999999}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: -0.19999999}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: -0.19999999}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, Skew: -0.19999999}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, Skew: -0.19999999}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.0049999, Skew: 0.66999996}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.5}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.5}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.5}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, RadiusOffset: 0.5}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: -0.5}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: -0.5}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: -0.5}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, RadiusOffset: -0.5}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.02}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.02}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 1, RadiusOffset: 0.02}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1, RadiusOffset: 0.02}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 3.5049999, Skew: 0.78}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 3.5049999, Skew: 0.78}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 3.5049999, Skew: 0.78}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 3.5049999, Skew: 0.78}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.5, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 0.5, TopSizeY: 0.1, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: 0.5, Revolutions: 1}, 6},
	{Shape{Type: "ring", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: 0.5, Revolutions: 1}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.0049999, RadiusOffset: 0.5, Skew: 0.66999996}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.995, RadiusOffset: 0.29999998, Skew: 0.75}, 7},
	{Shape{Type: "ring", CutEnd: 1, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutEnd: 1, Revolutions: 2.0049999, Skew: 0.66999996}, 6},
	{Shape{Type: "ring", CutEnd: 1, TwistBegin: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 0.25, TopShearX: 0.2, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, Revolutions: 2.0049999, Skew: 0.66999996}, 7},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 5},
	{Shape{Type: "ring", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 5},
	{Shape{Type: "ring", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutEnd: 1, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 6},
	{Shape{Type: "ring", CutEnd: 1, TopSizeX: 1, TopSizeY: 0.25, AdvancedCutBegin: 0.2, AdvancedCutEnd: 0.8, TaperX: -0.29999998, TaperY: 0.29999998, Revolutions: 2.0049999, Skew: -0.66999996}, 7},
	{Shape{Type: "sphere", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 1},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "sphere", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "sphere", CutEnd: 1, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 1},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutEnd: 1, Hollow: 0.5, TwistBegin: 0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "sphere", CutEnd: 1, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "sphere", CutEnd: 1, Hollow: 0.5, TwistBegin: -0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", CutEnd: 1, TwistBegin: -0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: -0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", CutEnd: 1, Hollow: 0.5, TwistBegin: -0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", CutEnd: 1, TopSizeX: 0.5, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 0.5, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", CutEnd: 1, Hollow: 0.5, TopSizeX: 0.5, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", CutEnd: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutBegin: 0.2, CutEnd: 0.8, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", CutEnd: 1, Hollow: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "box", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, TopShearX: 0.3, TopShearY: -0.2, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "box", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, TopShearX: 0.3, TopShearY: -0.2, AdvancedCutEnd: 1, Revolutions: 1}, 8},
	{Shape{Type: "box", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, TopShearX: 0.3, TopShearY: -0.2, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "cylinder", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "cylinder", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "cylinder", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "cylinder", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "cylinder", CutEnd: 1, TwistBegin: -0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "cylinder", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: -0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutEnd: 1, Hollow: 0.5, TwistBegin: -0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "cylinder", CutEnd: 1, TopSizeX: 0.5, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "cylinder", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 0.5, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutEnd: 1, Hollow: 0.5, TopSizeX: 0.5, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "cylinder", CutEnd: 1, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "cylinder", CutBegin: 0.2, CutEnd: 0.8, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutEnd: 1, Hollow: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "cylinder", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, TopShearX: 0.3, TopShearY: -0.2, AdvancedCutEnd: 1, Revolutions: 1}, 3},
	{Shape{Type: "cylinder", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, TopShearX: 0.3, TopShearY: -0.2, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "cylinder", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, TopShearX: 0.3, TopShearY: -0.2, AdvancedCutEnd: 1, Revolutions: 1}, 4},
	{Shape{Type: "prism", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "prism", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutEnd: 1, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "prism", CutBegin: 0.2, CutEnd: 0.8, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutEnd: 1, Hollow: 0.5, TwistEnd: 0.5, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutEnd: 1, TwistBegin: -0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "prism", CutBegin: 0.2, CutEnd: 0.8, TwistBegin: -0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutEnd: 1, Hollow: 0.5, TwistBegin: -0.25, TwistEnd: 0.25, TopSizeX: 1, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutEnd: 1, TopSizeX: 0.5, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "prism", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 0.5, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutEnd: 1, Hollow: 0.5, TopSizeX: 0.5, TopSizeY: 1, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutEnd: 1, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "prism", CutBegin: 0.2, CutEnd: 0.8, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutEnd: 1, Hollow: 0.5, AdvancedCutEnd: 1, Revolutions: 1}, 6},
	{Shape{Type: "prism", CutEnd: 1, TopSizeX: 1, TopSizeY: 1, TopShearX: 0.3, TopShearY: -0.2, AdvancedCutEnd: 1, Revolutions: 1}, 5},
	{Shape{Type: "prism", CutBegin: 0.2, CutEnd: 0.8, TopSizeX: 1, TopSizeY: 1, TopShearX: 0.3, TopShearY: -0.2, AdvancedCutEnd: 1, Revolutions: 1}, 7},
	{Shape{Type: "prism", CutEnd: 1, Hollow: 0.5, TopSizeX: 1, TopSizeY: 1, TopShearX: 0.3, TopShearY: -0.2, AdvancedCutEnd: 1, Revolutions: 1}, 6},
}
