// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: slgo.proto

// Package slgo.v1 is the link between a server holding grid connections
// and the clients attached to it.
//
// The division is that the server owns whatever breaks if a client
// restarts -- the circuit, its sequence numbers, retransmission,
// acknowledgements, the login and the capability URLs -- and nothing
// else.  It does not decode message bodies, hold an inventory,
// understand chat or know what a script is.
//
// A grid message crosses as its number and its undecoded bytes, so the
// server relays a message type it has never heard of and a client can
// be restarted as often as you like without the grid noticing.

package slgov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Grid_Stream_FullMethodName     = "/slgo.v1.Grid/Stream"
	Grid_ListAgents_FullMethodName = "/slgo.v1.Grid/ListAgents"
	Grid_Status_FullMethodName     = "/slgo.v1.Grid/Status"
	Grid_Cap_FullMethodName        = "/slgo.v1.Grid/Cap"
	Grid_Send_FullMethodName       = "/slgo.v1.Grid/Send"
)

// GridClient is the client API for Grid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GridClient interface {
	// Stream is the packet channel.  The client sends messages to put on
	// the circuit and receives the ones it has subscribed to.  Nothing
	// that is not a grid packet belongs here.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientPacket, ServerPacket], error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Cap makes an HTTP request against one of the agent's
	// capabilities.  The server holds the URLs and does the request; it
	// has no idea what any of them mean.  This is what keeps inventory,
	// asset upload and script compilation out of the server.
	Cap(ctx context.Context, in *CapRequest, opts ...grpc.CallOption) (*CapResponse, error)
	// Send puts one message on the circuit without opening a stream, for
	// a client that only wants to say one thing.
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type gridClient struct {
	cc grpc.ClientConnInterface
}

func NewGridClient(cc grpc.ClientConnInterface) GridClient {
	return &gridClient{cc}
}

func (c *gridClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientPacket, ServerPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Grid_ServiceDesc.Streams[0], Grid_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientPacket, ServerPacket]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grid_StreamClient = grpc.BidiStreamingClient[ClientPacket, ServerPacket]

func (c *gridClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, Grid_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Grid_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Cap(ctx context.Context, in *CapRequest, opts ...grpc.CallOption) (*CapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapResponse)
	err := c.cc.Invoke(ctx, Grid_Cap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Grid_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GridServer is the server API for Grid service.
// All implementations must embed UnimplementedGridServer
// for forward compatibility.
type GridServer interface {
	// Stream is the packet channel.  The client sends messages to put on
	// the circuit and receives the ones it has subscribed to.  Nothing
	// that is not a grid packet belongs here.
	Stream(grpc.BidiStreamingServer[ClientPacket, ServerPacket]) error
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Cap makes an HTTP request against one of the agent's
	// capabilities.  The server holds the URLs and does the request; it
	// has no idea what any of them mean.  This is what keeps inventory,
	// asset upload and script compilation out of the server.
	Cap(context.Context, *CapRequest) (*CapResponse, error)
	// Send puts one message on the circuit without opening a stream, for
	// a client that only wants to say one thing.
	Send(context.Context, *SendRequest) (*SendResponse, error)
	mustEmbedUnimplementedGridServer()
}

// UnimplementedGridServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGridServer struct{}

func (UnimplementedGridServer) Stream(grpc.BidiStreamingServer[ClientPacket, ServerPacket]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGridServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedGridServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedGridServer) Cap(context.Context, *CapRequest) (*CapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cap not implemented")
}
func (UnimplementedGridServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedGridServer) mustEmbedUnimplementedGridServer() {}
func (UnimplementedGridServer) testEmbeddedByValue()              {}

// UnsafeGridServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GridServer will
// result in compilation errors.
type UnsafeGridServer interface {
	mustEmbedUnimplementedGridServer()
}

func RegisterGridServer(s grpc.ServiceRegistrar, srv GridServer) {
	// If the following call panics, it indicates UnimplementedGridServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Grid_ServiceDesc, srv)
}

func _Grid_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GridServer).Stream(&grpc.GenericServerStream[ClientPacket, ServerPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grid_StreamServer = grpc.BidiStreamingServer[ClientPacket, ServerPacket]

func _Grid_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Cap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Cap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Cap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Cap(ctx, req.(*CapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Grid_ServiceDesc is the grpc.ServiceDesc for Grid service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grid_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slgo.v1.Grid",
	HandlerType: (*GridServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAgents",
			Handler:    _Grid_ListAgents_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Grid_Status_Handler,
		},
		{
			MethodName: "Cap",
			Handler:    _Grid_Cap_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Grid_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Grid_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "slgo.proto",
}
