// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: slgo.proto

// Package slgo.v1 is the link between a server holding grid connections
// and the clients attached to it.
//
// The division is that the server owns whatever breaks if a client
// restarts -- the circuit, its sequence numbers, retransmission,
// acknowledgements, the login and the capability URLs -- and nothing
// else.  It does not decode message bodies, hold an inventory,
// understand chat or know what a script is.
//
// A grid message crosses as its number and its undecoded bytes, so the
// server relays a message type it has never heard of and a client can
// be restarted as often as you like without the grid noticing.

package slgov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentEvent_Kind int32

const (
	AgentEvent_UNKNOWN        AgentEvent_Kind = 0
	AgentEvent_REGION_CHANGED AgentEvent_Kind = 1
	AgentEvent_DISCONNECTED   AgentEvent_Kind = 2
	AgentEvent_KICKED         AgentEvent_Kind = 3
)

// Enum value maps for AgentEvent_Kind.
var (
	AgentEvent_Kind_name = map[int32]string{
		0: "UNKNOWN",
		1: "REGION_CHANGED",
		2: "DISCONNECTED",
		3: "KICKED",
	}
	AgentEvent_Kind_value = map[string]int32{
		"UNKNOWN":        0,
		"REGION_CHANGED": 1,
		"DISCONNECTED":   2,
		"KICKED":         3,
	}
)

func (x AgentEvent_Kind) Enum() *AgentEvent_Kind {
	p := new(AgentEvent_Kind)
	*p = x
	return p
}

func (x AgentEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_slgo_proto_enumTypes[0].Descriptor()
}

func (AgentEvent_Kind) Type() protoreflect.EnumType {
	return &file_slgo_proto_enumTypes[0]
}

func (x AgentEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentEvent_Kind.Descriptor instead.
func (AgentEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{8, 0}
}

// ClientPacket is a message the client wants put on the circuit, or the
// opening frame naming the agent to attach to.
type ClientPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientPacket_Attach
	//	*ClientPacket_Message
	//	*ClientPacket_Subscribe
	Body          isClientPacket_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPacket) Reset() {
	*x = ClientPacket{}
	mi := &file_slgo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPacket) ProtoMessage() {}

func (x *ClientPacket) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPacket.ProtoReflect.Descriptor instead.
func (*ClientPacket) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{0}
}

func (x *ClientPacket) GetBody() isClientPacket_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientPacket) GetAttach() *Attach {
	if x != nil {
		if x, ok := x.Body.(*ClientPacket_Attach); ok {
			return x.Attach
		}
	}
	return nil
}

func (x *ClientPacket) GetMessage() *OutboundMessage {
	if x != nil {
		if x, ok := x.Body.(*ClientPacket_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ClientPacket) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Body.(*ClientPacket_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

type isClientPacket_Body interface {
	isClientPacket_Body()
}

type ClientPacket_Attach struct {
	Attach *Attach `protobuf:"bytes,1,opt,name=attach,proto3,oneof"`
}

type ClientPacket_Message struct {
	Message *OutboundMessage `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

type ClientPacket_Subscribe struct {
	// Which messages to relay is state of this stream, so it is
	// adjusted on the stream rather than by an RPC that would have no
	// way to say which stream it meant.
	Subscribe *Subscribe `protobuf:"bytes,3,opt,name=subscribe,proto3,oneof"`
}

func (*ClientPacket_Attach) isClientPacket_Body() {}

func (*ClientPacket_Message) isClientPacket_Body() {}

func (*ClientPacket_Subscribe) isClientPacket_Body() {}

// Subscribe adjusts what this stream relays.  Exactly one field is
// used: set replaces the subscription, add and remove adjust it.
type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           []string               `protobuf:"bytes,1,rep,name=set,proto3" json:"set,omitempty"`
	Add           []string               `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty"`
	Remove        []string               `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_slgo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{1}
}

func (x *Subscribe) GetSet() []string {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *Subscribe) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *Subscribe) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

// Attach must be the first frame on a stream.
type Attach struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Agent string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// Messages to relay, by template name.  "*" means everything.  Empty
	// means nothing until Subscribe says otherwise, which is the default
	// because a busy region will otherwise flood the link.
	Subscribe     []string `protobuf:"bytes,2,rep,name=subscribe,proto3" json:"subscribe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attach) Reset() {
	*x = Attach{}
	mi := &file_slgo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attach) ProtoMessage() {}

func (x *Attach) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attach.ProtoReflect.Descriptor instead.
func (*Attach) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{2}
}

func (x *Attach) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Attach) GetSubscribe() []string {
	if x != nil {
		return x.Subscribe
	}
	return nil
}

type OutboundMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message number, as slgo's msg.ID.  Name may be given instead
	// and is looked up in the template.
	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The encoded message body, without the packet header or the message
	// number.  The server frames it: sequence numbers and reliability
	// are circuit state and are not the client's to choose.
	Body          []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Reliable      bool   `protobuf:"varint,4,opt,name=reliable,proto3" json:"reliable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundMessage) Reset() {
	*x = OutboundMessage{}
	mi := &file_slgo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundMessage) ProtoMessage() {}

func (x *OutboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundMessage.ProtoReflect.Descriptor instead.
func (*OutboundMessage) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{3}
}

func (x *OutboundMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OutboundMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutboundMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *OutboundMessage) GetReliable() bool {
	if x != nil {
		return x.Reliable
	}
	return false
}

// ServerPacket is a message that arrived from the simulator, or a note
// about the connection.
type ServerPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerPacket_Message
	//	*ServerPacket_Attached
	//	*ServerPacket_Notice
	//	*ServerPacket_Event
	Body          isServerPacket_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket) Reset() {
	*x = ServerPacket{}
	mi := &file_slgo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket) ProtoMessage() {}

func (x *ServerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket.ProtoReflect.Descriptor instead.
func (*ServerPacket) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{4}
}

func (x *ServerPacket) GetBody() isServerPacket_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerPacket) GetMessage() *InboundMessage {
	if x != nil {
		if x, ok := x.Body.(*ServerPacket_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ServerPacket) GetAttached() *Attached {
	if x != nil {
		if x, ok := x.Body.(*ServerPacket_Attached); ok {
			return x.Attached
		}
	}
	return nil
}

func (x *ServerPacket) GetNotice() *AgentEvent {
	if x != nil {
		if x, ok := x.Body.(*ServerPacket_Notice); ok {
			return x.Notice
		}
	}
	return nil
}

func (x *ServerPacket) GetEvent() *InboundEvent {
	if x != nil {
		if x, ok := x.Body.(*ServerPacket_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isServerPacket_Body interface {
	isServerPacket_Body()
}

type ServerPacket_Message struct {
	Message *InboundMessage `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ServerPacket_Attached struct {
	Attached *Attached `protobuf:"bytes,2,opt,name=attached,proto3,oneof"`
}

type ServerPacket_Notice struct {
	// A note about the grid connection itself: it went away, it came
	// back.  Not grid traffic.
	Notice *AgentEvent `protobuf:"bytes,3,opt,name=notice,proto3,oneof"`
}

type ServerPacket_Event struct {
	// Something that arrived on the event queue rather than the UDP
	// circuit.  Its body is LLSD, not the binary message encoding, so
	// it cannot share InboundMessage.
	Event *InboundEvent `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

func (*ServerPacket_Message) isServerPacket_Body() {}

func (*ServerPacket_Attached) isServerPacket_Body() {}

func (*ServerPacket_Notice) isServerPacket_Body() {}

func (*ServerPacket_Event) isServerPacket_Body() {}

// InboundEvent is one entry from EventQueueGet.
//
// The queue carries what UDP no longer does: ParcelProperties,
// TeleportFinish, EstablishAgentCommunication and the rest.  A poll
// must be kept running continuously and its sequence acknowledged, so
// it belongs on the server for the same reason the circuit does -- a
// client restart would lose the sequence and drop events.
type InboundEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event name, as the queue gives it.  Some match a template
	// message and some have no UDP equivalent at all.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The event body, LLSD encoded.  The server does not look inside.
	Body          []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ReceivedAt    int64  `protobuf:"varint,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundEvent) Reset() {
	*x = InboundEvent{}
	mi := &file_slgo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundEvent) ProtoMessage() {}

func (x *InboundEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundEvent.ProtoReflect.Descriptor instead.
func (*InboundEvent) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{5}
}

func (x *InboundEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InboundEvent) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InboundEvent) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

type Attached struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attached) Reset() {
	*x = Attached{}
	mi := &file_slgo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attached) ProtoMessage() {}

func (x *Attached) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attached.ProtoReflect.Descriptor instead.
func (*Attached) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{6}
}

func (x *Attached) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type InboundMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The template's name for the message, empty when the number is not
	// in this server's template.  The body is relayed either way.
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Body     []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Sequence uint32 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Flags    uint32 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	// Microseconds since the epoch, when the datagram was read.
	ReceivedAt    int64 `protobuf:"varint,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundMessage) Reset() {
	*x = InboundMessage{}
	mi := &file_slgo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessage) ProtoMessage() {}

func (x *InboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessage.ProtoReflect.Descriptor instead.
func (*InboundMessage) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{7}
}

func (x *InboundMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InboundMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InboundMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InboundMessage) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *InboundMessage) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *InboundMessage) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

// AgentEvent is something that happened to the grid connection itself.
type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          AgentEvent_Kind        `protobuf:"varint,1,opt,name=kind,proto3,enum=slgo.v1.AgentEvent_Kind" json:"kind,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_slgo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{8}
}

func (x *AgentEvent) GetKind() AgentEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return AgentEvent_UNKNOWN
}

func (x *AgentEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type AgentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // the profile name the server hosts it under
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AvatarName     string                 `protobuf:"bytes,4,opt,name=avatar_name,json=avatarName,proto3" json:"avatar_name,omitempty"`
	Region         string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	ChannelVersion string                 `protobuf:"bytes,6,opt,name=channel_version,json=channelVersion,proto3" json:"channel_version,omitempty"`
	InventoryRoot  string                 `protobuf:"bytes,7,opt,name=inventory_root,json=inventoryRoot,proto3" json:"inventory_root,omitempty"`
	Caps           []string               `protobuf:"bytes,8,rep,name=caps,proto3" json:"caps,omitempty"`
	Connected      bool                   `protobuf:"varint,9,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_slgo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{9}
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentInfo) GetAvatarName() string {
	if x != nil {
		return x.AvatarName
	}
	return ""
}

func (x *AgentInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentInfo) GetChannelVersion() string {
	if x != nil {
		return x.ChannelVersion
	}
	return ""
}

func (x *AgentInfo) GetInventoryRoot() string {
	if x != nil {
		return x.InventoryRoot
	}
	return ""
}

func (x *AgentInfo) GetCaps() []string {
	if x != nil {
		return x.Caps
	}
	return nil
}

func (x *AgentInfo) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_slgo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{10}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_slgo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{11}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_slgo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{12}
}

func (x *StatusRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Agent           *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	PacketsIn       uint64                 `protobuf:"varint,2,opt,name=packets_in,json=packetsIn,proto3" json:"packets_in,omitempty"`
	PacketsOut      uint64                 `protobuf:"varint,3,opt,name=packets_out,json=packetsOut,proto3" json:"packets_out,omitempty"`
	BytesIn         uint64                 `protobuf:"varint,4,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut        uint64                 `protobuf:"varint,5,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	Resent          uint64                 `protobuf:"varint,6,opt,name=resent,proto3" json:"resent,omitempty"`
	Abandoned       uint64                 `protobuf:"varint,7,opt,name=abandoned,proto3" json:"abandoned,omitempty"`
	Duplicates      uint64                 `protobuf:"varint,8,opt,name=duplicates,proto3" json:"duplicates,omitempty"`
	Undecodable     uint64                 `protobuf:"varint,9,opt,name=undecodable,proto3" json:"undecodable,omitempty"`
	UnknownMessages uint64                 `protobuf:"varint,10,opt,name=unknown_messages,json=unknownMessages,proto3" json:"unknown_messages,omitempty"`
	Clients         int32                  `protobuf:"varint,11,opt,name=clients,proto3" json:"clients,omitempty"`
	// Messages nobody has registered for, by template name.  This is how
	// a protocol change announces itself.
	Unhandled     map[string]uint64 `protobuf:"bytes,12,rep,name=unhandled,proto3" json:"unhandled,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_slgo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{13}
}

func (x *StatusResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *StatusResponse) GetPacketsIn() uint64 {
	if x != nil {
		return x.PacketsIn
	}
	return 0
}

func (x *StatusResponse) GetPacketsOut() uint64 {
	if x != nil {
		return x.PacketsOut
	}
	return 0
}

func (x *StatusResponse) GetBytesIn() uint64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *StatusResponse) GetBytesOut() uint64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *StatusResponse) GetResent() uint64 {
	if x != nil {
		return x.Resent
	}
	return 0
}

func (x *StatusResponse) GetAbandoned() uint64 {
	if x != nil {
		return x.Abandoned
	}
	return 0
}

func (x *StatusResponse) GetDuplicates() uint64 {
	if x != nil {
		return x.Duplicates
	}
	return 0
}

func (x *StatusResponse) GetUndecodable() uint64 {
	if x != nil {
		return x.Undecodable
	}
	return 0
}

func (x *StatusResponse) GetUnknownMessages() uint64 {
	if x != nil {
		return x.UnknownMessages
	}
	return 0
}

func (x *StatusResponse) GetClients() int32 {
	if x != nil {
		return x.Clients
	}
	return 0
}

func (x *StatusResponse) GetUnhandled() map[string]uint64 {
	if x != nil {
		return x.Unhandled
	}
	return nil
}

type CapRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Agent       string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Cap         string                 `protobuf:"bytes,2,opt,name=cap,proto3" json:"cap,omitempty"`       // capability name, e.g. "InventoryAPIv3"
	Method      string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // default GET
	Path        string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`     // appended to the capability URL
	Body        []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	ContentType string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// An absolute URL to use instead of a named capability.
	//
	// Asset upload needs this: the first step posts to a capability and
	// the simulator answers with a one-shot uploader URL to post the
	// bytes to.  Without it a client would have to reach the simulator
	// itself, which is exactly the coupling the server exists to avoid.
	//
	// Only URLs the simulator has handed us are accepted, so this cannot
	// be used to make the server fetch something arbitrary.
	Url           string `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapRequest) Reset() {
	*x = CapRequest{}
	mi := &file_slgo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapRequest) ProtoMessage() {}

func (x *CapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapRequest.ProtoReflect.Descriptor instead.
func (*CapRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{14}
}

func (x *CapRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *CapRequest) GetCap() string {
	if x != nil {
		return x.Cap
	}
	return ""
}

func (x *CapRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CapRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CapRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CapRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CapRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapResponse) Reset() {
	*x = CapResponse{}
	mi := &file_slgo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapResponse) ProtoMessage() {}

func (x *CapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapResponse.ProtoReflect.Descriptor instead.
func (*CapResponse) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{15}
}

func (x *CapResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CapResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Message       *OutboundMessage       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_slgo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{16}
}

func (x *SendRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *SendRequest) GetMessage() *OutboundMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_slgo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{17}
}

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_slgo_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{18}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type PresenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Agent string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// Draw distance in metres, which is how far the simulator is asked
	// to describe things.  Zero leaves it as it is; anything else sets
	// it, and the response reports what it ended up as.
	DrawDistance  float32 `protobuf:"fixed32,2,opt,name=draw_distance,json=drawDistance,proto3" json:"draw_distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceRequest) Reset() {
	*x = PresenceRequest{}
	mi := &file_slgo_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceRequest) ProtoMessage() {}

func (x *PresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceRequest.ProtoReflect.Descriptor instead.
func (*PresenceRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{19}
}

func (x *PresenceRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *PresenceRequest) GetDrawDistance() float32 {
	if x != nil {
		return x.DrawDistance
	}
	return 0
}

type PresenceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where the avatar is, in region coordinates, as last reported by
	// the simulator.  Precise after a teleport or a region entry, and to
	// the nearest metre while walking, which is all
	// CoarseLocationUpdate carries.
	Position *Vector3 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	// Where it is looking.
	LookAt *Vector3 `protobuf:"bytes,2,opt,name=look_at,json=lookAt,proto3" json:"look_at,omitempty"`
	// The camera the simulator is told about.  It follows the avatar.
	Camera       *Vector3 `protobuf:"bytes,3,opt,name=camera,proto3" json:"camera,omitempty"`
	DrawDistance float32  `protobuf:"fixed32,4,opt,name=draw_distance,json=drawDistance,proto3" json:"draw_distance,omitempty"`
	RegionHandle uint64   `protobuf:"varint,5,opt,name=region_handle,json=regionHandle,proto3" json:"region_handle,omitempty"`
	Region       string   `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	// The group the avatar is acting as, which a parcel's build and
	// script rights are usually granted to rather than to individuals.
	// It arrives at login and whenever it changes, so a client that
	// attached later would never have heard it.
	ActiveGroup   string `protobuf:"bytes,7,opt,name=active_group,json=activeGroup,proto3" json:"active_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceResponse) Reset() {
	*x = PresenceResponse{}
	mi := &file_slgo_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceResponse) ProtoMessage() {}

func (x *PresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceResponse.ProtoReflect.Descriptor instead.
func (*PresenceResponse) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{20}
}

func (x *PresenceResponse) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PresenceResponse) GetLookAt() *Vector3 {
	if x != nil {
		return x.LookAt
	}
	return nil
}

func (x *PresenceResponse) GetCamera() *Vector3 {
	if x != nil {
		return x.Camera
	}
	return nil
}

func (x *PresenceResponse) GetDrawDistance() float32 {
	if x != nil {
		return x.DrawDistance
	}
	return 0
}

func (x *PresenceResponse) GetRegionHandle() uint64 {
	if x != nil {
		return x.RegionHandle
	}
	return 0
}

func (x *PresenceResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PresenceResponse) GetActiveGroup() string {
	if x != nil {
		return x.ActiveGroup
	}
	return ""
}

type ObjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Agent string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// Named, if set, returns only objects with this name.  A name is
	// only known if something has asked for it, so an object whose name
	// has never been requested does not match anything.
	Named string `protobuf:"bytes,2,opt,name=named,proto3" json:"named,omitempty"`
	// Id, if set, returns just that object.
	Id            string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectsRequest) Reset() {
	*x = ObjectsRequest{}
	mi := &file_slgo_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectsRequest) ProtoMessage() {}

func (x *ObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectsRequest.ProtoReflect.Descriptor instead.
func (*ObjectsRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{21}
}

func (x *ObjectsRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *ObjectsRequest) GetNamed() string {
	if x != nil {
		return x.Named
	}
	return ""
}

func (x *ObjectsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ObjectInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Local uint32                 `protobuf:"varint,2,opt,name=local,proto3" json:"local,omitempty"`
	// Parent is the local id of the root this is linked under, zero for
	// a root.
	Parent uint32 `protobuf:"varint,3,opt,name=parent,proto3" json:"parent,omitempty"`
	// Pcode is 9 for a prim and 47 for an avatar.
	Pcode    uint32   `protobuf:"varint,4,opt,name=pcode,proto3" json:"pcode,omitempty"`
	Scale    *Vector3 `protobuf:"bytes,5,opt,name=scale,proto3" json:"scale,omitempty"`
	Position *Vector3 `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	// Name is empty until something has asked for it.  Owner is filled
	// in by a compressed update as well as by asking.
	Name  string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Owner string `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	// TextureEntry is the packed per face appearance, when one has been
	// seen.  It usually arrives only in a compressed update.
	TextureEntry []byte `protobuf:"bytes,9,opt,name=texture_entry,json=textureEntry,proto3" json:"texture_entry,omitempty"`
	// Text is the floating text above the object.
	Text          string `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectInfo) Reset() {
	*x = ObjectInfo{}
	mi := &file_slgo_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectInfo) ProtoMessage() {}

func (x *ObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectInfo.ProtoReflect.Descriptor instead.
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{22}
}

func (x *ObjectInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectInfo) GetLocal() uint32 {
	if x != nil {
		return x.Local
	}
	return 0
}

func (x *ObjectInfo) GetParent() uint32 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *ObjectInfo) GetPcode() uint32 {
	if x != nil {
		return x.Pcode
	}
	return 0
}

func (x *ObjectInfo) GetScale() *Vector3 {
	if x != nil {
		return x.Scale
	}
	return nil
}

func (x *ObjectInfo) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ObjectInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ObjectInfo) GetTextureEntry() []byte {
	if x != nil {
		return x.TextureEntry
	}
	return nil
}

func (x *ObjectInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ObjectsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Objects []*ObjectInfo          `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	// Known is how many objects the session has heard about in total,
	// which is what the filtered list was drawn from.
	Known         int32 `protobuf:"varint,2,opt,name=known,proto3" json:"known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectsResponse) Reset() {
	*x = ObjectsResponse{}
	mi := &file_slgo_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectsResponse) ProtoMessage() {}

func (x *ObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectsResponse.ProtoReflect.Descriptor instead.
func (*ObjectsResponse) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{23}
}

func (x *ObjectsResponse) GetObjects() []*ObjectInfo {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ObjectsResponse) GetKnown() int32 {
	if x != nil {
		return x.Known
	}
	return 0
}

type RegionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionRequest) Reset() {
	*x = RegionRequest{}
	mi := &file_slgo_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionRequest) ProtoMessage() {}

func (x *RegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionRequest.ProtoReflect.Descriptor instead.
func (*RegionRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{24}
}

func (x *RegionRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type RegionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Handle        uint64                 `protobuf:"varint,2,opt,name=handle,proto3" json:"handle,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	FlagsExtended uint64                 `protobuf:"varint,5,opt,name=flags_extended,json=flagsExtended,proto3" json:"flags_extended,omitempty"`
	// Access is the maturity rating; owner is the estate owner.
	Access        uint32  `protobuf:"varint,6,opt,name=access,proto3" json:"access,omitempty"`
	Owner         string  `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	EstateManager bool    `protobuf:"varint,8,opt,name=estate_manager,json=estateManager,proto3" json:"estate_manager,omitempty"`
	WaterHeight   float32 `protobuf:"fixed32,9,opt,name=water_height,json=waterHeight,proto3" json:"water_height,omitempty"`
	ProductName   string  `protobuf:"bytes,10,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductSku    string  `protobuf:"bytes,11,opt,name=product_sku,json=productSku,proto3" json:"product_sku,omitempty"`
	ColoName      string  `protobuf:"bytes,12,opt,name=colo_name,json=coloName,proto3" json:"colo_name,omitempty"`
	CpuClass      int32   `protobuf:"varint,13,opt,name=cpu_class,json=cpuClass,proto3" json:"cpu_class,omitempty"`
	CpuRatio      int32   `protobuf:"varint,14,opt,name=cpu_ratio,json=cpuRatio,proto3" json:"cpu_ratio,omitempty"`
	Protocols     uint64  `protobuf:"varint,15,opt,name=protocols,proto3" json:"protocols,omitempty"`
	// Known is false until the handshake has arrived.
	Known         bool `protobuf:"varint,16,opt,name=known,proto3" json:"known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionInfo) Reset() {
	*x = RegionInfo{}
	mi := &file_slgo_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionInfo) ProtoMessage() {}

func (x *RegionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionInfo.ProtoReflect.Descriptor instead.
func (*RegionInfo) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{25}
}

func (x *RegionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegionInfo) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *RegionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegionInfo) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *RegionInfo) GetFlagsExtended() uint64 {
	if x != nil {
		return x.FlagsExtended
	}
	return 0
}

func (x *RegionInfo) GetAccess() uint32 {
	if x != nil {
		return x.Access
	}
	return 0
}

func (x *RegionInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RegionInfo) GetEstateManager() bool {
	if x != nil {
		return x.EstateManager
	}
	return false
}

func (x *RegionInfo) GetWaterHeight() float32 {
	if x != nil {
		return x.WaterHeight
	}
	return 0
}

func (x *RegionInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *RegionInfo) GetProductSku() string {
	if x != nil {
		return x.ProductSku
	}
	return ""
}

func (x *RegionInfo) GetColoName() string {
	if x != nil {
		return x.ColoName
	}
	return ""
}

func (x *RegionInfo) GetCpuClass() int32 {
	if x != nil {
		return x.CpuClass
	}
	return 0
}

func (x *RegionInfo) GetCpuRatio() int32 {
	if x != nil {
		return x.CpuRatio
	}
	return 0
}

func (x *RegionInfo) GetProtocols() uint64 {
	if x != nil {
		return x.Protocols
	}
	return 0
}

func (x *RegionInfo) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_slgo_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{26}
}

func (x *FlushRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type FlushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Forgotten is how many objects the cache held.
	Forgotten     int32 `protobuf:"varint,1,opt,name=forgotten,proto3" json:"forgotten,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_slgo_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{27}
}

func (x *FlushResponse) GetForgotten() int32 {
	if x != nil {
		return x.Forgotten
	}
	return 0
}

var File_slgo_proto protoreflect.FileDescriptor

const file_slgo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"slgo.proto\x12\aslgo.v1\"\xab\x01\n" +
	"\fClientPacket\x12)\n" +
	"\x06attach\x18\x01 \x01(\v2\x0f.slgo.v1.AttachH\x00R\x06attach\x124\n" +
	"\amessage\x18\x02 \x01(\v2\x18.slgo.v1.OutboundMessageH\x00R\amessage\x122\n" +
	"\tsubscribe\x18\x03 \x01(\v2\x12.slgo.v1.SubscribeH\x00R\tsubscribeB\x06\n" +
	"\x04body\"G\n" +
	"\tSubscribe\x12\x10\n" +
	"\x03set\x18\x01 \x03(\tR\x03set\x12\x10\n" +
	"\x03add\x18\x02 \x03(\tR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\"<\n" +
	"\x06Attach\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x1c\n" +
	"\tsubscribe\x18\x02 \x03(\tR\tsubscribe\"e\n" +
	"\x0fOutboundMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1a\n" +
	"\breliable\x18\x04 \x01(\bR\breliable\"\xda\x01\n" +
	"\fServerPacket\x123\n" +
	"\amessage\x18\x01 \x01(\v2\x17.slgo.v1.InboundMessageH\x00R\amessage\x12/\n" +
	"\battached\x18\x02 \x01(\v2\x11.slgo.v1.AttachedH\x00R\battached\x12-\n" +
	"\x06notice\x18\x03 \x01(\v2\x13.slgo.v1.AgentEventH\x00R\x06notice\x12-\n" +
	"\x05event\x18\x04 \x01(\v2\x15.slgo.v1.InboundEventH\x00R\x05eventB\x06\n" +
	"\x04body\"]\n" +
	"\fInboundEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x1f\n" +
	"\vreceived_at\x18\x03 \x01(\x03R\n" +
	"receivedAt\"4\n" +
	"\bAttached\x12(\n" +
	"\x05agent\x18\x01 \x01(\v2\x12.slgo.v1.AgentInfoR\x05agent\"\x9b\x01\n" +
	"\x0eInboundMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\rR\bsequence\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\x12\x1f\n" +
	"\vreceived_at\x18\x06 \x01(\x03R\n" +
	"receivedAt\"\x99\x01\n" +
	"\n" +
	"AgentEvent\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.slgo.v1.AgentEvent.KindR\x04kind\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"E\n" +
	"\x04Kind\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eREGION_CHANGED\x10\x01\x12\x10\n" +
	"\fDISCONNECTED\x10\x02\x12\n" +
	"\n" +
	"\x06KICKED\x10\x03\"\x94\x02\n" +
	"\tAgentInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vavatar_name\x18\x04 \x01(\tR\n" +
	"avatarName\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12'\n" +
	"\x0fchannel_version\x18\x06 \x01(\tR\x0echannelVersion\x12%\n" +
	"\x0einventory_root\x18\a \x01(\tR\rinventoryRoot\x12\x12\n" +
	"\x04caps\x18\b \x03(\tR\x04caps\x12\x1c\n" +
	"\tconnected\x18\t \x01(\bR\tconnected\"\x13\n" +
	"\x11ListAgentsRequest\"@\n" +
	"\x12ListAgentsResponse\x12*\n" +
	"\x06agents\x18\x01 \x03(\v2\x12.slgo.v1.AgentInfoR\x06agents\"%\n" +
	"\rStatusRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\"\xf3\x03\n" +
	"\x0eStatusResponse\x12(\n" +
	"\x05agent\x18\x01 \x01(\v2\x12.slgo.v1.AgentInfoR\x05agent\x12\x1d\n" +
	"\n" +
	"packets_in\x18\x02 \x01(\x04R\tpacketsIn\x12\x1f\n" +
	"\vpackets_out\x18\x03 \x01(\x04R\n" +
	"packetsOut\x12\x19\n" +
	"\bbytes_in\x18\x04 \x01(\x04R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x05 \x01(\x04R\bbytesOut\x12\x16\n" +
	"\x06resent\x18\x06 \x01(\x04R\x06resent\x12\x1c\n" +
	"\tabandoned\x18\a \x01(\x04R\tabandoned\x12\x1e\n" +
	"\n" +
	"duplicates\x18\b \x01(\x04R\n" +
	"duplicates\x12 \n" +
	"\vundecodable\x18\t \x01(\x04R\vundecodable\x12)\n" +
	"\x10unknown_messages\x18\n" +
	" \x01(\x04R\x0funknownMessages\x12\x18\n" +
	"\aclients\x18\v \x01(\x05R\aclients\x12D\n" +
	"\tunhandled\x18\f \x03(\v2&.slgo.v1.StatusResponse.UnhandledEntryR\tunhandled\x1a<\n" +
	"\x0eUnhandledEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xa9\x01\n" +
	"\n" +
	"CapRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x10\n" +
	"\x03cap\x18\x02 \x01(\tR\x03cap\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\"9\n" +
	"\vCapResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\"W\n" +
	"\vSendRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x122\n" +
	"\amessage\x18\x02 \x01(\v2\x18.slgo.v1.OutboundMessageR\amessage\"\x0e\n" +
	"\fSendResponse\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"L\n" +
	"\x0fPresenceRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12#\n" +
	"\rdraw_distance\x18\x02 \x01(\x02R\fdrawDistance\"\x9a\x02\n" +
	"\x10PresenceResponse\x12,\n" +
	"\bposition\x18\x01 \x01(\v2\x10.slgo.v1.Vector3R\bposition\x12)\n" +
	"\alook_at\x18\x02 \x01(\v2\x10.slgo.v1.Vector3R\x06lookAt\x12(\n" +
	"\x06camera\x18\x03 \x01(\v2\x10.slgo.v1.Vector3R\x06camera\x12#\n" +
	"\rdraw_distance\x18\x04 \x01(\x02R\fdrawDistance\x12#\n" +
	"\rregion_handle\x18\x05 \x01(\x04R\fregionHandle\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12!\n" +
	"\factive_group\x18\a \x01(\tR\vactiveGroup\"L\n" +
	"\x0eObjectsRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x14\n" +
	"\x05named\x18\x02 \x01(\tR\x05named\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\x99\x02\n" +
	"\n" +
	"ObjectInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05local\x18\x02 \x01(\rR\x05local\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\rR\x06parent\x12\x14\n" +
	"\x05pcode\x18\x04 \x01(\rR\x05pcode\x12&\n" +
	"\x05scale\x18\x05 \x01(\v2\x10.slgo.v1.Vector3R\x05scale\x12,\n" +
	"\bposition\x18\x06 \x01(\v2\x10.slgo.v1.Vector3R\bposition\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12#\n" +
	"\rtexture_entry\x18\t \x01(\fR\ftextureEntry\x12\x12\n" +
	"\x04text\x18\n" +
	" \x01(\tR\x04text\"V\n" +
	"\x0fObjectsResponse\x12-\n" +
	"\aobjects\x18\x01 \x03(\v2\x13.slgo.v1.ObjectInfoR\aobjects\x12\x14\n" +
	"\x05known\x18\x02 \x01(\x05R\x05known\"%\n" +
	"\rRegionRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\"\xcc\x03\n" +
	"\n" +
	"RegionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\x04R\x06handle\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\x12%\n" +
	"\x0eflags_extended\x18\x05 \x01(\x04R\rflagsExtended\x12\x16\n" +
	"\x06access\x18\x06 \x01(\rR\x06access\x12\x14\n" +
	"\x05owner\x18\a \x01(\tR\x05owner\x12%\n" +
	"\x0eestate_manager\x18\b \x01(\bR\restateManager\x12!\n" +
	"\fwater_height\x18\t \x01(\x02R\vwaterHeight\x12!\n" +
	"\fproduct_name\x18\n" +
	" \x01(\tR\vproductName\x12\x1f\n" +
	"\vproduct_sku\x18\v \x01(\tR\n" +
	"productSku\x12\x1b\n" +
	"\tcolo_name\x18\f \x01(\tR\bcoloName\x12\x1b\n" +
	"\tcpu_class\x18\r \x01(\x05R\bcpuClass\x12\x1b\n" +
	"\tcpu_ratio\x18\x0e \x01(\x05R\bcpuRatio\x12\x1c\n" +
	"\tprotocols\x18\x0f \x01(\x04R\tprotocols\x12\x14\n" +
	"\x05known\x18\x10 \x01(\bR\x05known\"$\n" +
	"\fFlushRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\"-\n" +
	"\rFlushResponse\x12\x1c\n" +
	"\tforgotten\x18\x01 \x01(\x05R\tforgotten2\x99\x04\n" +
	"\x04Grid\x12:\n" +
	"\x06Stream\x12\x15.slgo.v1.ClientPacket\x1a\x15.slgo.v1.ServerPacket(\x010\x01\x12E\n" +
	"\n" +
	"ListAgents\x12\x1a.slgo.v1.ListAgentsRequest\x1a\x1b.slgo.v1.ListAgentsResponse\x129\n" +
	"\x06Status\x12\x16.slgo.v1.StatusRequest\x1a\x17.slgo.v1.StatusResponse\x12?\n" +
	"\bPresence\x12\x18.slgo.v1.PresenceRequest\x1a\x19.slgo.v1.PresenceResponse\x12<\n" +
	"\aObjects\x12\x17.slgo.v1.ObjectsRequest\x1a\x18.slgo.v1.ObjectsResponse\x125\n" +
	"\x06Region\x12\x16.slgo.v1.RegionRequest\x1a\x13.slgo.v1.RegionInfo\x126\n" +
	"\x05Flush\x12\x15.slgo.v1.FlushRequest\x1a\x16.slgo.v1.FlushResponse\x120\n" +
	"\x03Cap\x12\x13.slgo.v1.CapRequest\x1a\x14.slgo.v1.CapResponse\x123\n" +
	"\x04Send\x12\x14.slgo.v1.SendRequest\x1a\x15.slgo.v1.SendResponseB\x13Z\x11slgo/proto/slgov1b\x06proto3"

var (
	file_slgo_proto_rawDescOnce sync.Once
	file_slgo_proto_rawDescData []byte
)

func file_slgo_proto_rawDescGZIP() []byte {
	file_slgo_proto_rawDescOnce.Do(func() {
		file_slgo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slgo_proto_rawDesc), len(file_slgo_proto_rawDesc)))
	})
	return file_slgo_proto_rawDescData
}

var file_slgo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_slgo_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_slgo_proto_goTypes = []any{
	(AgentEvent_Kind)(0),       // 0: slgo.v1.AgentEvent.Kind
	(*ClientPacket)(nil),       // 1: slgo.v1.ClientPacket
	(*Subscribe)(nil),          // 2: slgo.v1.Subscribe
	(*Attach)(nil),             // 3: slgo.v1.Attach
	(*OutboundMessage)(nil),    // 4: slgo.v1.OutboundMessage
	(*ServerPacket)(nil),       // 5: slgo.v1.ServerPacket
	(*InboundEvent)(nil),       // 6: slgo.v1.InboundEvent
	(*Attached)(nil),           // 7: slgo.v1.Attached
	(*InboundMessage)(nil),     // 8: slgo.v1.InboundMessage
	(*AgentEvent)(nil),         // 9: slgo.v1.AgentEvent
	(*AgentInfo)(nil),          // 10: slgo.v1.AgentInfo
	(*ListAgentsRequest)(nil),  // 11: slgo.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil), // 12: slgo.v1.ListAgentsResponse
	(*StatusRequest)(nil),      // 13: slgo.v1.StatusRequest
	(*StatusResponse)(nil),     // 14: slgo.v1.StatusResponse
	(*CapRequest)(nil),         // 15: slgo.v1.CapRequest
	(*CapResponse)(nil),        // 16: slgo.v1.CapResponse
	(*SendRequest)(nil),        // 17: slgo.v1.SendRequest
	(*SendResponse)(nil),       // 18: slgo.v1.SendResponse
	(*Vector3)(nil),            // 19: slgo.v1.Vector3
	(*PresenceRequest)(nil),    // 20: slgo.v1.PresenceRequest
	(*PresenceResponse)(nil),   // 21: slgo.v1.PresenceResponse
	(*ObjectsRequest)(nil),     // 22: slgo.v1.ObjectsRequest
	(*ObjectInfo)(nil),         // 23: slgo.v1.ObjectInfo
	(*ObjectsResponse)(nil),    // 24: slgo.v1.ObjectsResponse
	(*RegionRequest)(nil),      // 25: slgo.v1.RegionRequest
	(*RegionInfo)(nil),         // 26: slgo.v1.RegionInfo
	(*FlushRequest)(nil),       // 27: slgo.v1.FlushRequest
	(*FlushResponse)(nil),      // 28: slgo.v1.FlushResponse
	nil,                        // 29: slgo.v1.StatusResponse.UnhandledEntry
}
var file_slgo_proto_depIdxs = []int32{
	3,  // 0: slgo.v1.ClientPacket.attach:type_name -> slgo.v1.Attach
	4,  // 1: slgo.v1.ClientPacket.message:type_name -> slgo.v1.OutboundMessage
	2,  // 2: slgo.v1.ClientPacket.subscribe:type_name -> slgo.v1.Subscribe
	8,  // 3: slgo.v1.ServerPacket.message:type_name -> slgo.v1.InboundMessage
	7,  // 4: slgo.v1.ServerPacket.attached:type_name -> slgo.v1.Attached
	9,  // 5: slgo.v1.ServerPacket.notice:type_name -> slgo.v1.AgentEvent
	6,  // 6: slgo.v1.ServerPacket.event:type_name -> slgo.v1.InboundEvent
	10, // 7: slgo.v1.Attached.agent:type_name -> slgo.v1.AgentInfo
	0,  // 8: slgo.v1.AgentEvent.kind:type_name -> slgo.v1.AgentEvent.Kind
	10, // 9: slgo.v1.ListAgentsResponse.agents:type_name -> slgo.v1.AgentInfo
	10, // 10: slgo.v1.StatusResponse.agent:type_name -> slgo.v1.AgentInfo
	29, // 11: slgo.v1.StatusResponse.unhandled:type_name -> slgo.v1.StatusResponse.UnhandledEntry
	4,  // 12: slgo.v1.SendRequest.message:type_name -> slgo.v1.OutboundMessage
	19, // 13: slgo.v1.PresenceResponse.position:type_name -> slgo.v1.Vector3
	19, // 14: slgo.v1.PresenceResponse.look_at:type_name -> slgo.v1.Vector3
	19, // 15: slgo.v1.PresenceResponse.camera:type_name -> slgo.v1.Vector3
	19, // 16: slgo.v1.ObjectInfo.scale:type_name -> slgo.v1.Vector3
	19, // 17: slgo.v1.ObjectInfo.position:type_name -> slgo.v1.Vector3
	23, // 18: slgo.v1.ObjectsResponse.objects:type_name -> slgo.v1.ObjectInfo
	1,  // 19: slgo.v1.Grid.Stream:input_type -> slgo.v1.ClientPacket
	11, // 20: slgo.v1.Grid.ListAgents:input_type -> slgo.v1.ListAgentsRequest
	13, // 21: slgo.v1.Grid.Status:input_type -> slgo.v1.StatusRequest
	20, // 22: slgo.v1.Grid.Presence:input_type -> slgo.v1.PresenceRequest
	22, // 23: slgo.v1.Grid.Objects:input_type -> slgo.v1.ObjectsRequest
	25, // 24: slgo.v1.Grid.Region:input_type -> slgo.v1.RegionRequest
	27, // 25: slgo.v1.Grid.Flush:input_type -> slgo.v1.FlushRequest
	15, // 26: slgo.v1.Grid.Cap:input_type -> slgo.v1.CapRequest
	17, // 27: slgo.v1.Grid.Send:input_type -> slgo.v1.SendRequest
	5,  // 28: slgo.v1.Grid.Stream:output_type -> slgo.v1.ServerPacket
	12, // 29: slgo.v1.Grid.ListAgents:output_type -> slgo.v1.ListAgentsResponse
	14, // 30: slgo.v1.Grid.Status:output_type -> slgo.v1.StatusResponse
	21, // 31: slgo.v1.Grid.Presence:output_type -> slgo.v1.PresenceResponse
	24, // 32: slgo.v1.Grid.Objects:output_type -> slgo.v1.ObjectsResponse
	26, // 33: slgo.v1.Grid.Region:output_type -> slgo.v1.RegionInfo
	28, // 34: slgo.v1.Grid.Flush:output_type -> slgo.v1.FlushResponse
	16, // 35: slgo.v1.Grid.Cap:output_type -> slgo.v1.CapResponse
	18, // 36: slgo.v1.Grid.Send:output_type -> slgo.v1.SendResponse
	28, // [28:37] is the sub-list for method output_type
	19, // [19:28] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_slgo_proto_init() }
func file_slgo_proto_init() {
	if File_slgo_proto != nil {
		return
	}
	file_slgo_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientPacket_Attach)(nil),
		(*ClientPacket_Message)(nil),
		(*ClientPacket_Subscribe)(nil),
	}
	file_slgo_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerPacket_Message)(nil),
		(*ServerPacket_Attached)(nil),
		(*ServerPacket_Notice)(nil),
		(*ServerPacket_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slgo_proto_rawDesc), len(file_slgo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slgo_proto_goTypes,
		DependencyIndexes: file_slgo_proto_depIdxs,
		EnumInfos:         file_slgo_proto_enumTypes,
		MessageInfos:      file_slgo_proto_msgTypes,
	}.Build()
	File_slgo_proto = out.File
	file_slgo_proto_goTypes = nil
	file_slgo_proto_depIdxs = nil
}
