// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: slgo.proto

// Package slgo.v1 is the link between a server holding grid connections
// and the clients attached to it.
//
// The division is that the server owns whatever breaks if a client
// restarts -- the circuit, its sequence numbers, retransmission,
// acknowledgements, the login and the capability URLs -- and nothing
// else.  It does not decode message bodies, hold an inventory,
// understand chat or know what a script is.
//
// A grid message crosses as its number and its undecoded bytes, so the
// server relays a message type it has never heard of and a client can
// be restarted as often as you like without the grid noticing.

package slgov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentEvent_Kind int32

const (
	AgentEvent_UNKNOWN        AgentEvent_Kind = 0
	AgentEvent_REGION_CHANGED AgentEvent_Kind = 1
	AgentEvent_DISCONNECTED   AgentEvent_Kind = 2
	AgentEvent_KICKED         AgentEvent_Kind = 3
)

// Enum value maps for AgentEvent_Kind.
var (
	AgentEvent_Kind_name = map[int32]string{
		0: "UNKNOWN",
		1: "REGION_CHANGED",
		2: "DISCONNECTED",
		3: "KICKED",
	}
	AgentEvent_Kind_value = map[string]int32{
		"UNKNOWN":        0,
		"REGION_CHANGED": 1,
		"DISCONNECTED":   2,
		"KICKED":         3,
	}
)

func (x AgentEvent_Kind) Enum() *AgentEvent_Kind {
	p := new(AgentEvent_Kind)
	*p = x
	return p
}

func (x AgentEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_slgo_proto_enumTypes[0].Descriptor()
}

func (AgentEvent_Kind) Type() protoreflect.EnumType {
	return &file_slgo_proto_enumTypes[0]
}

func (x AgentEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentEvent_Kind.Descriptor instead.
func (AgentEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{7, 0}
}

// ClientPacket is a message the client wants put on the circuit, or the
// opening frame naming the agent to attach to.
type ClientPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientPacket_Attach
	//	*ClientPacket_Message
	//	*ClientPacket_Subscribe
	Body          isClientPacket_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPacket) Reset() {
	*x = ClientPacket{}
	mi := &file_slgo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPacket) ProtoMessage() {}

func (x *ClientPacket) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPacket.ProtoReflect.Descriptor instead.
func (*ClientPacket) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{0}
}

func (x *ClientPacket) GetBody() isClientPacket_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientPacket) GetAttach() *Attach {
	if x != nil {
		if x, ok := x.Body.(*ClientPacket_Attach); ok {
			return x.Attach
		}
	}
	return nil
}

func (x *ClientPacket) GetMessage() *OutboundMessage {
	if x != nil {
		if x, ok := x.Body.(*ClientPacket_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ClientPacket) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Body.(*ClientPacket_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

type isClientPacket_Body interface {
	isClientPacket_Body()
}

type ClientPacket_Attach struct {
	Attach *Attach `protobuf:"bytes,1,opt,name=attach,proto3,oneof"`
}

type ClientPacket_Message struct {
	Message *OutboundMessage `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

type ClientPacket_Subscribe struct {
	// Which messages to relay is state of this stream, so it is
	// adjusted on the stream rather than by an RPC that would have no
	// way to say which stream it meant.
	Subscribe *Subscribe `protobuf:"bytes,3,opt,name=subscribe,proto3,oneof"`
}

func (*ClientPacket_Attach) isClientPacket_Body() {}

func (*ClientPacket_Message) isClientPacket_Body() {}

func (*ClientPacket_Subscribe) isClientPacket_Body() {}

// Subscribe adjusts what this stream relays.  Exactly one field is
// used: set replaces the subscription, add and remove adjust it.
type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           []string               `protobuf:"bytes,1,rep,name=set,proto3" json:"set,omitempty"`
	Add           []string               `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty"`
	Remove        []string               `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_slgo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{1}
}

func (x *Subscribe) GetSet() []string {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *Subscribe) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *Subscribe) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

// Attach must be the first frame on a stream.
type Attach struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Agent string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// Messages to relay, by template name.  "*" means everything.  Empty
	// means nothing until Subscribe says otherwise, which is the default
	// because a busy region will otherwise flood the link.
	Subscribe     []string `protobuf:"bytes,2,rep,name=subscribe,proto3" json:"subscribe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attach) Reset() {
	*x = Attach{}
	mi := &file_slgo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attach) ProtoMessage() {}

func (x *Attach) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attach.ProtoReflect.Descriptor instead.
func (*Attach) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{2}
}

func (x *Attach) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Attach) GetSubscribe() []string {
	if x != nil {
		return x.Subscribe
	}
	return nil
}

type OutboundMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message number, as slgo's msg.ID.  Name may be given instead
	// and is looked up in the template.
	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The encoded message body, without the packet header or the message
	// number.  The server frames it: sequence numbers and reliability
	// are circuit state and are not the client's to choose.
	Body          []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Reliable      bool   `protobuf:"varint,4,opt,name=reliable,proto3" json:"reliable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundMessage) Reset() {
	*x = OutboundMessage{}
	mi := &file_slgo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundMessage) ProtoMessage() {}

func (x *OutboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundMessage.ProtoReflect.Descriptor instead.
func (*OutboundMessage) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{3}
}

func (x *OutboundMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OutboundMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutboundMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *OutboundMessage) GetReliable() bool {
	if x != nil {
		return x.Reliable
	}
	return false
}

// ServerPacket is a message that arrived from the simulator, or a note
// about the connection.
type ServerPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerPacket_Message
	//	*ServerPacket_Attached
	//	*ServerPacket_Event
	Body          isServerPacket_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket) Reset() {
	*x = ServerPacket{}
	mi := &file_slgo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket) ProtoMessage() {}

func (x *ServerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket.ProtoReflect.Descriptor instead.
func (*ServerPacket) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{4}
}

func (x *ServerPacket) GetBody() isServerPacket_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerPacket) GetMessage() *InboundMessage {
	if x != nil {
		if x, ok := x.Body.(*ServerPacket_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ServerPacket) GetAttached() *Attached {
	if x != nil {
		if x, ok := x.Body.(*ServerPacket_Attached); ok {
			return x.Attached
		}
	}
	return nil
}

func (x *ServerPacket) GetEvent() *AgentEvent {
	if x != nil {
		if x, ok := x.Body.(*ServerPacket_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isServerPacket_Body interface {
	isServerPacket_Body()
}

type ServerPacket_Message struct {
	Message *InboundMessage `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ServerPacket_Attached struct {
	Attached *Attached `protobuf:"bytes,2,opt,name=attached,proto3,oneof"`
}

type ServerPacket_Event struct {
	Event *AgentEvent `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

func (*ServerPacket_Message) isServerPacket_Body() {}

func (*ServerPacket_Attached) isServerPacket_Body() {}

func (*ServerPacket_Event) isServerPacket_Body() {}

type Attached struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attached) Reset() {
	*x = Attached{}
	mi := &file_slgo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attached) ProtoMessage() {}

func (x *Attached) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attached.ProtoReflect.Descriptor instead.
func (*Attached) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{5}
}

func (x *Attached) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type InboundMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The template's name for the message, empty when the number is not
	// in this server's template.  The body is relayed either way.
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Body     []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Sequence uint32 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Flags    uint32 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	// Microseconds since the epoch, when the datagram was read.
	ReceivedAt    int64 `protobuf:"varint,6,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundMessage) Reset() {
	*x = InboundMessage{}
	mi := &file_slgo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessage) ProtoMessage() {}

func (x *InboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessage.ProtoReflect.Descriptor instead.
func (*InboundMessage) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{6}
}

func (x *InboundMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InboundMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InboundMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InboundMessage) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *InboundMessage) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *InboundMessage) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

// AgentEvent is something that happened to the grid connection itself.
type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          AgentEvent_Kind        `protobuf:"varint,1,opt,name=kind,proto3,enum=slgo.v1.AgentEvent_Kind" json:"kind,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_slgo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{7}
}

func (x *AgentEvent) GetKind() AgentEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return AgentEvent_UNKNOWN
}

func (x *AgentEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type AgentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // the profile name the server hosts it under
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AvatarName     string                 `protobuf:"bytes,4,opt,name=avatar_name,json=avatarName,proto3" json:"avatar_name,omitempty"`
	Region         string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	ChannelVersion string                 `protobuf:"bytes,6,opt,name=channel_version,json=channelVersion,proto3" json:"channel_version,omitempty"`
	InventoryRoot  string                 `protobuf:"bytes,7,opt,name=inventory_root,json=inventoryRoot,proto3" json:"inventory_root,omitempty"`
	Caps           []string               `protobuf:"bytes,8,rep,name=caps,proto3" json:"caps,omitempty"`
	Connected      bool                   `protobuf:"varint,9,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_slgo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{8}
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentInfo) GetAvatarName() string {
	if x != nil {
		return x.AvatarName
	}
	return ""
}

func (x *AgentInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AgentInfo) GetChannelVersion() string {
	if x != nil {
		return x.ChannelVersion
	}
	return ""
}

func (x *AgentInfo) GetInventoryRoot() string {
	if x != nil {
		return x.InventoryRoot
	}
	return ""
}

func (x *AgentInfo) GetCaps() []string {
	if x != nil {
		return x.Caps
	}
	return nil
}

func (x *AgentInfo) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_slgo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{9}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_slgo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{10}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_slgo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{11}
}

func (x *StatusRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Agent           *AgentInfo             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	PacketsIn       uint64                 `protobuf:"varint,2,opt,name=packets_in,json=packetsIn,proto3" json:"packets_in,omitempty"`
	PacketsOut      uint64                 `protobuf:"varint,3,opt,name=packets_out,json=packetsOut,proto3" json:"packets_out,omitempty"`
	BytesIn         uint64                 `protobuf:"varint,4,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut        uint64                 `protobuf:"varint,5,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	Resent          uint64                 `protobuf:"varint,6,opt,name=resent,proto3" json:"resent,omitempty"`
	Abandoned       uint64                 `protobuf:"varint,7,opt,name=abandoned,proto3" json:"abandoned,omitempty"`
	Duplicates      uint64                 `protobuf:"varint,8,opt,name=duplicates,proto3" json:"duplicates,omitempty"`
	Undecodable     uint64                 `protobuf:"varint,9,opt,name=undecodable,proto3" json:"undecodable,omitempty"`
	UnknownMessages uint64                 `protobuf:"varint,10,opt,name=unknown_messages,json=unknownMessages,proto3" json:"unknown_messages,omitempty"`
	Clients         int32                  `protobuf:"varint,11,opt,name=clients,proto3" json:"clients,omitempty"`
	// Messages nobody has registered for, by template name.  This is how
	// a protocol change announces itself.
	Unhandled     map[string]uint64 `protobuf:"bytes,12,rep,name=unhandled,proto3" json:"unhandled,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_slgo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{12}
}

func (x *StatusResponse) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *StatusResponse) GetPacketsIn() uint64 {
	if x != nil {
		return x.PacketsIn
	}
	return 0
}

func (x *StatusResponse) GetPacketsOut() uint64 {
	if x != nil {
		return x.PacketsOut
	}
	return 0
}

func (x *StatusResponse) GetBytesIn() uint64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *StatusResponse) GetBytesOut() uint64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *StatusResponse) GetResent() uint64 {
	if x != nil {
		return x.Resent
	}
	return 0
}

func (x *StatusResponse) GetAbandoned() uint64 {
	if x != nil {
		return x.Abandoned
	}
	return 0
}

func (x *StatusResponse) GetDuplicates() uint64 {
	if x != nil {
		return x.Duplicates
	}
	return 0
}

func (x *StatusResponse) GetUndecodable() uint64 {
	if x != nil {
		return x.Undecodable
	}
	return 0
}

func (x *StatusResponse) GetUnknownMessages() uint64 {
	if x != nil {
		return x.UnknownMessages
	}
	return 0
}

func (x *StatusResponse) GetClients() int32 {
	if x != nil {
		return x.Clients
	}
	return 0
}

func (x *StatusResponse) GetUnhandled() map[string]uint64 {
	if x != nil {
		return x.Unhandled
	}
	return nil
}

type CapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Cap           string                 `protobuf:"bytes,2,opt,name=cap,proto3" json:"cap,omitempty"`       // capability name, e.g. "InventoryAPIv3"
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // default GET
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`     // appended to the capability URL
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapRequest) Reset() {
	*x = CapRequest{}
	mi := &file_slgo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapRequest) ProtoMessage() {}

func (x *CapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapRequest.ProtoReflect.Descriptor instead.
func (*CapRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{13}
}

func (x *CapRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *CapRequest) GetCap() string {
	if x != nil {
		return x.Cap
	}
	return ""
}

func (x *CapRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CapRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CapRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CapRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type CapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapResponse) Reset() {
	*x = CapResponse{}
	mi := &file_slgo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapResponse) ProtoMessage() {}

func (x *CapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapResponse.ProtoReflect.Descriptor instead.
func (*CapResponse) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{14}
}

func (x *CapResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CapResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Message       *OutboundMessage       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_slgo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{15}
}

func (x *SendRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *SendRequest) GetMessage() *OutboundMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_slgo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slgo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_slgo_proto_rawDescGZIP(), []int{16}
}

var File_slgo_proto protoreflect.FileDescriptor

const file_slgo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"slgo.proto\x12\aslgo.v1\"\xab\x01\n" +
	"\fClientPacket\x12)\n" +
	"\x06attach\x18\x01 \x01(\v2\x0f.slgo.v1.AttachH\x00R\x06attach\x124\n" +
	"\amessage\x18\x02 \x01(\v2\x18.slgo.v1.OutboundMessageH\x00R\amessage\x122\n" +
	"\tsubscribe\x18\x03 \x01(\v2\x12.slgo.v1.SubscribeH\x00R\tsubscribeB\x06\n" +
	"\x04body\"G\n" +
	"\tSubscribe\x12\x10\n" +
	"\x03set\x18\x01 \x03(\tR\x03set\x12\x10\n" +
	"\x03add\x18\x02 \x03(\tR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove\"<\n" +
	"\x06Attach\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x1c\n" +
	"\tsubscribe\x18\x02 \x03(\tR\tsubscribe\"e\n" +
	"\x0fOutboundMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1a\n" +
	"\breliable\x18\x04 \x01(\bR\breliable\"\xa9\x01\n" +
	"\fServerPacket\x123\n" +
	"\amessage\x18\x01 \x01(\v2\x17.slgo.v1.InboundMessageH\x00R\amessage\x12/\n" +
	"\battached\x18\x02 \x01(\v2\x11.slgo.v1.AttachedH\x00R\battached\x12+\n" +
	"\x05event\x18\x03 \x01(\v2\x13.slgo.v1.AgentEventH\x00R\x05eventB\x06\n" +
	"\x04body\"4\n" +
	"\bAttached\x12(\n" +
	"\x05agent\x18\x01 \x01(\v2\x12.slgo.v1.AgentInfoR\x05agent\"\x9b\x01\n" +
	"\x0eInboundMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\rR\bsequence\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\x12\x1f\n" +
	"\vreceived_at\x18\x06 \x01(\x03R\n" +
	"receivedAt\"\x99\x01\n" +
	"\n" +
	"AgentEvent\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.slgo.v1.AgentEvent.KindR\x04kind\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"E\n" +
	"\x04Kind\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eREGION_CHANGED\x10\x01\x12\x10\n" +
	"\fDISCONNECTED\x10\x02\x12\n" +
	"\n" +
	"\x06KICKED\x10\x03\"\x94\x02\n" +
	"\tAgentInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vavatar_name\x18\x04 \x01(\tR\n" +
	"avatarName\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12'\n" +
	"\x0fchannel_version\x18\x06 \x01(\tR\x0echannelVersion\x12%\n" +
	"\x0einventory_root\x18\a \x01(\tR\rinventoryRoot\x12\x12\n" +
	"\x04caps\x18\b \x03(\tR\x04caps\x12\x1c\n" +
	"\tconnected\x18\t \x01(\bR\tconnected\"\x13\n" +
	"\x11ListAgentsRequest\"@\n" +
	"\x12ListAgentsResponse\x12*\n" +
	"\x06agents\x18\x01 \x03(\v2\x12.slgo.v1.AgentInfoR\x06agents\"%\n" +
	"\rStatusRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\"\xf3\x03\n" +
	"\x0eStatusResponse\x12(\n" +
	"\x05agent\x18\x01 \x01(\v2\x12.slgo.v1.AgentInfoR\x05agent\x12\x1d\n" +
	"\n" +
	"packets_in\x18\x02 \x01(\x04R\tpacketsIn\x12\x1f\n" +
	"\vpackets_out\x18\x03 \x01(\x04R\n" +
	"packetsOut\x12\x19\n" +
	"\bbytes_in\x18\x04 \x01(\x04R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x05 \x01(\x04R\bbytesOut\x12\x16\n" +
	"\x06resent\x18\x06 \x01(\x04R\x06resent\x12\x1c\n" +
	"\tabandoned\x18\a \x01(\x04R\tabandoned\x12\x1e\n" +
	"\n" +
	"duplicates\x18\b \x01(\x04R\n" +
	"duplicates\x12 \n" +
	"\vundecodable\x18\t \x01(\x04R\vundecodable\x12)\n" +
	"\x10unknown_messages\x18\n" +
	" \x01(\x04R\x0funknownMessages\x12\x18\n" +
	"\aclients\x18\v \x01(\x05R\aclients\x12D\n" +
	"\tunhandled\x18\f \x03(\v2&.slgo.v1.StatusResponse.UnhandledEntryR\tunhandled\x1a<\n" +
	"\x0eUnhandledEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x97\x01\n" +
	"\n" +
	"CapRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x10\n" +
	"\x03cap\x18\x02 \x01(\tR\x03cap\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\"9\n" +
	"\vCapResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\"W\n" +
	"\vSendRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x122\n" +
	"\amessage\x18\x02 \x01(\v2\x18.slgo.v1.OutboundMessageR\amessage\"\x0e\n" +
	"\fSendResponse2\xab\x02\n" +
	"\x04Grid\x12:\n" +
	"\x06Stream\x12\x15.slgo.v1.ClientPacket\x1a\x15.slgo.v1.ServerPacket(\x010\x01\x12E\n" +
	"\n" +
	"ListAgents\x12\x1a.slgo.v1.ListAgentsRequest\x1a\x1b.slgo.v1.ListAgentsResponse\x129\n" +
	"\x06Status\x12\x16.slgo.v1.StatusRequest\x1a\x17.slgo.v1.StatusResponse\x120\n" +
	"\x03Cap\x12\x13.slgo.v1.CapRequest\x1a\x14.slgo.v1.CapResponse\x123\n" +
	"\x04Send\x12\x14.slgo.v1.SendRequest\x1a\x15.slgo.v1.SendResponseB\x13Z\x11slgo/proto/slgov1b\x06proto3"

var (
	file_slgo_proto_rawDescOnce sync.Once
	file_slgo_proto_rawDescData []byte
)

func file_slgo_proto_rawDescGZIP() []byte {
	file_slgo_proto_rawDescOnce.Do(func() {
		file_slgo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slgo_proto_rawDesc), len(file_slgo_proto_rawDesc)))
	})
	return file_slgo_proto_rawDescData
}

var file_slgo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_slgo_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_slgo_proto_goTypes = []any{
	(AgentEvent_Kind)(0),       // 0: slgo.v1.AgentEvent.Kind
	(*ClientPacket)(nil),       // 1: slgo.v1.ClientPacket
	(*Subscribe)(nil),          // 2: slgo.v1.Subscribe
	(*Attach)(nil),             // 3: slgo.v1.Attach
	(*OutboundMessage)(nil),    // 4: slgo.v1.OutboundMessage
	(*ServerPacket)(nil),       // 5: slgo.v1.ServerPacket
	(*Attached)(nil),           // 6: slgo.v1.Attached
	(*InboundMessage)(nil),     // 7: slgo.v1.InboundMessage
	(*AgentEvent)(nil),         // 8: slgo.v1.AgentEvent
	(*AgentInfo)(nil),          // 9: slgo.v1.AgentInfo
	(*ListAgentsRequest)(nil),  // 10: slgo.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil), // 11: slgo.v1.ListAgentsResponse
	(*StatusRequest)(nil),      // 12: slgo.v1.StatusRequest
	(*StatusResponse)(nil),     // 13: slgo.v1.StatusResponse
	(*CapRequest)(nil),         // 14: slgo.v1.CapRequest
	(*CapResponse)(nil),        // 15: slgo.v1.CapResponse
	(*SendRequest)(nil),        // 16: slgo.v1.SendRequest
	(*SendResponse)(nil),       // 17: slgo.v1.SendResponse
	nil,                        // 18: slgo.v1.StatusResponse.UnhandledEntry
}
var file_slgo_proto_depIdxs = []int32{
	3,  // 0: slgo.v1.ClientPacket.attach:type_name -> slgo.v1.Attach
	4,  // 1: slgo.v1.ClientPacket.message:type_name -> slgo.v1.OutboundMessage
	2,  // 2: slgo.v1.ClientPacket.subscribe:type_name -> slgo.v1.Subscribe
	7,  // 3: slgo.v1.ServerPacket.message:type_name -> slgo.v1.InboundMessage
	6,  // 4: slgo.v1.ServerPacket.attached:type_name -> slgo.v1.Attached
	8,  // 5: slgo.v1.ServerPacket.event:type_name -> slgo.v1.AgentEvent
	9,  // 6: slgo.v1.Attached.agent:type_name -> slgo.v1.AgentInfo
	0,  // 7: slgo.v1.AgentEvent.kind:type_name -> slgo.v1.AgentEvent.Kind
	9,  // 8: slgo.v1.ListAgentsResponse.agents:type_name -> slgo.v1.AgentInfo
	9,  // 9: slgo.v1.StatusResponse.agent:type_name -> slgo.v1.AgentInfo
	18, // 10: slgo.v1.StatusResponse.unhandled:type_name -> slgo.v1.StatusResponse.UnhandledEntry
	4,  // 11: slgo.v1.SendRequest.message:type_name -> slgo.v1.OutboundMessage
	1,  // 12: slgo.v1.Grid.Stream:input_type -> slgo.v1.ClientPacket
	10, // 13: slgo.v1.Grid.ListAgents:input_type -> slgo.v1.ListAgentsRequest
	12, // 14: slgo.v1.Grid.Status:input_type -> slgo.v1.StatusRequest
	14, // 15: slgo.v1.Grid.Cap:input_type -> slgo.v1.CapRequest
	16, // 16: slgo.v1.Grid.Send:input_type -> slgo.v1.SendRequest
	5,  // 17: slgo.v1.Grid.Stream:output_type -> slgo.v1.ServerPacket
	11, // 18: slgo.v1.Grid.ListAgents:output_type -> slgo.v1.ListAgentsResponse
	13, // 19: slgo.v1.Grid.Status:output_type -> slgo.v1.StatusResponse
	15, // 20: slgo.v1.Grid.Cap:output_type -> slgo.v1.CapResponse
	17, // 21: slgo.v1.Grid.Send:output_type -> slgo.v1.SendResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_slgo_proto_init() }
func file_slgo_proto_init() {
	if File_slgo_proto != nil {
		return
	}
	file_slgo_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientPacket_Attach)(nil),
		(*ClientPacket_Message)(nil),
		(*ClientPacket_Subscribe)(nil),
	}
	file_slgo_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerPacket_Message)(nil),
		(*ServerPacket_Attached)(nil),
		(*ServerPacket_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slgo_proto_rawDesc), len(file_slgo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slgo_proto_goTypes,
		DependencyIndexes: file_slgo_proto_depIdxs,
		EnumInfos:         file_slgo_proto_enumTypes,
		MessageInfos:      file_slgo_proto_msgTypes,
	}.Build()
	File_slgo_proto = out.File
	file_slgo_proto_goTypes = nil
	file_slgo_proto_depIdxs = nil
}
