// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: slgo.proto

// Package slgo.v1 is the link between a server holding grid connections
// and the clients attached to it.
//
// The division is that the server owns whatever breaks if a client
// restarts -- the circuit, its sequence numbers, retransmission,
// acknowledgements, the login and the capability URLs -- and nothing
// else.  It does not decode message bodies, hold an inventory,
// understand chat or know what a script is.
//
// A grid message crosses as its number and its undecoded bytes, so the
// server relays a message type it has never heard of and a client can
// be restarted as often as you like without the grid noticing.

package slgov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Grid_Login_FullMethodName            = "/slgo.v1.Grid/Login"
	Grid_Stream_FullMethodName           = "/slgo.v1.Grid/Stream"
	Grid_ListAgents_FullMethodName       = "/slgo.v1.Grid/ListAgents"
	Grid_Status_FullMethodName           = "/slgo.v1.Grid/Status"
	Grid_Host_FullMethodName             = "/slgo.v1.Grid/Host"
	Grid_Logout_FullMethodName           = "/slgo.v1.Grid/Logout"
	Grid_Presence_FullMethodName         = "/slgo.v1.Grid/Presence"
	Grid_Objects_FullMethodName          = "/slgo.v1.Grid/Objects"
	Grid_Attachments_FullMethodName      = "/slgo.v1.Grid/Attachments"
	Grid_Region_FullMethodName           = "/slgo.v1.Grid/Region"
	Grid_Land_FullMethodName             = "/slgo.v1.Grid/Land"
	Grid_Neighbours_FullMethodName       = "/slgo.v1.Grid/Neighbours"
	Grid_Flush_FullMethodName            = "/slgo.v1.Grid/Flush"
	Grid_Cap_FullMethodName              = "/slgo.v1.Grid/Cap"
	Grid_Send_FullMethodName             = "/slgo.v1.Grid/Send"
	Grid_Control_FullMethodName          = "/slgo.v1.Grid/Control"
	Grid_Move_FullMethodName             = "/slgo.v1.Grid/Move"
	Grid_Face_FullMethodName             = "/slgo.v1.Grid/Face"
	Grid_Halt_FullMethodName             = "/slgo.v1.Grid/Halt"
	Grid_Friends_FullMethodName          = "/slgo.v1.Grid/Friends"
	Grid_NoteFriend_FullMethodName       = "/slgo.v1.Grid/NoteFriend"
	Grid_Handled_FullMethodName          = "/slgo.v1.Grid/Handled"
	Grid_ViewerCredential_FullMethodName = "/slgo.v1.Grid/ViewerCredential"
)

// GridClient is the client API for Grid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GridClient interface {
	// Login authenticates a caller, BOTH WAYS, before anything else is
	// accepted. Two calls of one message type; see LoginRequest.
	//
	// slgod holds a live Second Life session, so an unauthenticated one
	// reachable off this machine is an open invitation to drive somebody
	// else's avatar. The exchange is the same one slrund uses, from the
	// same package.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Stream is the packet channel.  The client sends messages to put on
	// the circuit and receives the ones it has subscribed to.  Nothing
	// that is not a grid packet belongs here.
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientPacket, ServerPacket], error)
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Host brings a session up that is not running, and Logout puts one
	// down and keeps it down.
	//
	// Both are deliberate acts by a person, which is why they are their
	// own methods rather than something that happens as a side effect of
	// attaching.  Logging an avatar in is visible on the grid -- an
	// arrival, a presence, a notice to whoever is watching -- and should
	// not follow from a typo in a stale config file.
	//
	// Logout is remembered.  A session that was told to stop stays
	// stopped, so that somebody using that avatar in a viewer is not
	// fighting the daemon for it, and comes back only when asked for by
	// name.
	Host(ctx context.Context, in *HostRequest, opts ...grpc.CallOption) (*HostResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// Presence reads where the avatar is and what it can see, and can
	// change the draw distance.
	//
	// Both belong to the server.  AgentUpdate is what puts a session in
	// the simulator's interest list, it has to keep being sent, and the
	// interest list is worked out from the camera rather than from where
	// the avatar is -- so a client that owned this would empty the
	// interest list for every other client by exiting.  A client can ask
	// what it is and ask for it to be changed; it cannot hold it.
	Presence(ctx context.Context, in *PresenceRequest, opts ...grpc.CallOption) (*PresenceResponse, error)
	// Objects is what the region has told the session about itself.
	//
	// The server holds this for the same reason it holds the camera: a
	// region describes itself once, when the avatar arrives, and a
	// client that attaches a minute later is never told any of it.  The
	// server was there to hear it, so the server remembers.  It still
	// has no idea what any of the objects are for.
	Objects(ctx context.Context, in *ObjectsRequest, opts ...grpc.CallOption) (*ObjectsResponse, error)
	// Attachments is what the simulator last said an avatar is wearing:
	// the attachment list at the end of AvatarAppearance.
	//
	// Held by the server for the reason Objects is.  The simulator sends
	// it unasked -- about other avatars when they arrive, about this one
	// when it is baked -- so a client that attached afterwards has no
	// other way to hear it.
	//
	// It is the simulator's own account, which the region's object
	// descriptions are not: a viewer keeps an avatar a cloud until what
	// it has been shown matches this list, and a client can tell "on,
	// and not described yet" from "not on" the same way.
	Attachments(ctx context.Context, in *AttachmentsRequest, opts ...grpc.CallOption) (*AttachmentsResponse, error)
	// Region is what the simulator said about itself in the handshake,
	// which happens once, before any client is listening.
	Region(ctx context.Context, in *RegionRequest, opts ...grpc.CallOption) (*RegionInfo, error)
	// Land is what the session was told about the ground it is on: the
	// parcel it was pushed on arrival, and the region's parcel overlay.
	//
	// Both arrive unasked, once, before any client is listening, and the
	// overlay is the half that cannot be asked for again -- four packets
	// on arrival and none afterwards, however politely a client asks.
	// The parcel can be asked for, in a tenth of a second, so only its
	// name and local id come back here: enough to say what the session
	// believes it is standing on when the asking fails or is not worth
	// the wait.
	Land(ctx context.Context, in *LandRequest, opts ...grpc.CallOption) (*LandInfo, error)
	// Neighbours reads the circuits held to the regions AROUND that one,
	// and can turn them on and off.
	//
	// The same division as Presence, for the same reason.  A simulator
	// will not hand an avatar over a border to a client that holds no
	// circuit to the region on the other side, and holding one costs a
	// socket and a share of the traffic for as long as it is held -- so
	// it belongs to the server, which owns the circuits and pays for
	// them, and a client asks what it is and asks for it to be changed.
	//
	// Worth changing while a session is up, which is why this is not a
	// daemon-wide switch: one avatar is being driven by a person who
	// wants to walk out of the region, and the next is running a
	// benchmark that wants nothing but the region it is in.
	Neighbours(ctx context.Context, in *NeighboursRequest, opts ...grpc.CallOption) (*NeighboursResponse, error)
	// Flush empties the object cache.
	//
	// It is done automatically when the region changes, since everything
	// cached then describes somewhere else.  This is for a client that
	// knows the cache is wrong for a reason the server cannot see.
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	// Cap makes an HTTP request against one of the agent's
	// capabilities.  The server holds the URLs and does the request; it
	// has no idea what any of them mean.  This is what keeps inventory,
	// asset upload and script compilation out of the server.
	Cap(ctx context.Context, in *CapRequest, opts ...grpc.CallOption) (*CapResponse, error)
	// Send puts one message on the circuit without opening a stream, for
	// a client that only wants to say one thing.
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	// Control sends one AgentUpdate carrying control flags, and forgets
	// them.  Sitting on the ground and standing up are nothing but this.
	//
	// It belongs to the server for the reason Presence does, and more
	// sharply.  An AgentUpdate is not just its flags: it carries the
	// camera, its three axes and the draw distance, and the simulator
	// scopes its interest list by them.  A client has none of that -- it
	// knows a position from Presence and no axes at all -- so a client
	// that built one would be guessing at the camera and inventing a draw
	// distance, and the simulator would believe it until the server's own
	// update a second later put it back.  The server owns the camera, so
	// the server is the only thing that can send an update that is right
	// about everything except the one bit being asked for.
	//
	// A primitive rather than a sit call and a stand call, because it is
	// the same shape as everything else that moves an avatar: fly, stop,
	// jump, and the nudges a walk is made of.
	Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	// Move walks the avatar to a place in its region, and streams how it
	// is going until it is over.
	//
	// It belongs to the server for Control's reason and one more.  A walk
	// is a control flag held down on AgentUpdate, ten times a second,
	// with the body turned toward the target from where the avatar
	// actually is -- and the one that holds a flag down has to be the one
	// certain to let go of it.  A client that crashed mid-walk would leave
	// the last update it caused saying "forward", and the avatar would
	// walk until it met something.  The server steers, and a client that
	// goes away -- this stream ending, for any reason -- stops the avatar.
	//
	// The stream is a MoveEvent about every quarter of a second while the
	// avatar moves, and one final event, whose state is anything but
	// MOVING, after which it ends.  A walk that cannot start -- a target
	// outside the region, an avatar that is sitting, a viewer driving it
	// -- is that final event and nothing else, before anything is sent.
	//
	// One walk per avatar.  A second Move takes the first over without
	// stopping in between, and the first stream ends CANCELLED with the
	// reason "superseded"; Halt ends it with "halted" and stops the
	// avatar.
	//
	// It walks a straight line and avoids nothing.  What is in the way is
	// the client's to steer round, by asking again with a different
	// target; the server notices only that the avatar has stopped getting
	// closer, which is BLOCKED.
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MoveEvent], error)
	// Face turns the avatar toward a place, or to a heading, without
	// moving it.  Every update after it keeps the facing, the server's
	// own once-a-second ones included.  A walk under way is ended by it,
	// as a superseded one.
	Face(ctx context.Context, in *FaceRequest, opts ...grpc.CallOption) (*FaceResponse, error)
	// Halt ends any walk and stops the avatar.
	Halt(ctx context.Context, in *HaltRequest, opts ...grpc.CallOption) (*HaltResponse, error)
	// Friends is who this avatar's friends are and which of them are
	// logged in.
	//
	// The server holds this for the same reason it holds the region's
	// objects: the grid says it once, to whoever was there. The list
	// itself arrives only in the login response -- it is on no message
	// the simulator ever sends -- and online status arrives as a burst
	// of OnlineNotification seconds after the handshake, long before a
	// client can attach. Neither can be asked for again.
	Friends(ctx context.Context, in *FriendsRequest, opts ...grpc.CallOption) (*FriendsResponse, error)
	// NoteFriend records a friendship the client watched being formed.
	//
	// Accepting an offer is the one case the grid never reports. The
	// side that offers is told twice -- an instant message saying so
	// and an OnlineNotification -- and the side that accepts is told
	// nothing whatsoever, because it was the one that did it. A viewer
	// has the same hole and fills it the same way, by adding the friend
	// to its own list (LLAvatarTracker::formFriendship).
	//
	// So the client, which understands what it just sent, tells the
	// server, which holds what a client restart would lose. The server
	// still decodes nothing.
	NoteFriend(ctx context.Context, in *NoteFriendRequest, opts ...grpc.CallOption) (*NoteFriendResponse, error)
	// Handled tells the server an offer it is keeping has been dealt
	// with -- accepted, declined, or put aside for good -- so that it
	// drops out of the record and out of every other client's list.
	//
	// The server keeps the offers that arrive for an avatar whether or
	// not anybody is attached: a teleport offered, a request to be
	// offered one, an item handed over, an offer of friendship, an
	// invitation into a group.  Each is answered by quoting an id that
	// arrives once and cannot be asked for again, and the daemon is the
	// one thing that is always there to hear it; a client that attaches
	// later is handed what is still waiting in Attached.offers.  That
	// makes this the second place the server reads a message body, after
	// the teleport and seat answers it reads for itself, and for the same
	// reason: it is the session's business whether or not anybody is
	// listening.
	//
	// A client calls it BEFORE sending its answer, and the answer says
	// whether to go on.  Two clients attached to one avatar see the same
	// offers, and the first to say it is dealing with one is the one
	// that does; the second is told who got there first and how, and
	// sends nothing.  A client whose answer then fails to go out calls
	// again with undo, and the offer is put back for everybody.
	Handled(ctx context.Context, in *HandledRequest, opts ...grpc.CallOption) (*HandledResponse, error)
	// ViewerCredential mints a password a real viewer may log in with
	// ONCE, so that a session can be handed to a person without any
	// password being typed or stored anywhere.
	//
	// A call of its own rather than a field of StatusResponse because
	// asking is not free: every call makes a fresh secret and drops the
	// one before it, which is not something a client watching the
	// counters should do by accident.  Where the endpoint is and whether
	// a viewer is on it are facts and cost nothing to read, so they
	// travel in StatusResponse.viewer instead.
	ViewerCredential(ctx context.Context, in *ViewerCredentialRequest, opts ...grpc.CallOption) (*ViewerCredentialResponse, error)
}

type gridClient struct {
	cc grpc.ClientConnInterface
}

func NewGridClient(cc grpc.ClientConnInterface) GridClient {
	return &gridClient{cc}
}

func (c *gridClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Grid_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientPacket, ServerPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Grid_ServiceDesc.Streams[0], Grid_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientPacket, ServerPacket]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grid_StreamClient = grpc.BidiStreamingClient[ClientPacket, ServerPacket]

func (c *gridClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, Grid_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Grid_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Host(ctx context.Context, in *HostRequest, opts ...grpc.CallOption) (*HostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostResponse)
	err := c.cc.Invoke(ctx, Grid_Host_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, Grid_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Presence(ctx context.Context, in *PresenceRequest, opts ...grpc.CallOption) (*PresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresenceResponse)
	err := c.cc.Invoke(ctx, Grid_Presence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Objects(ctx context.Context, in *ObjectsRequest, opts ...grpc.CallOption) (*ObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectsResponse)
	err := c.cc.Invoke(ctx, Grid_Objects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Attachments(ctx context.Context, in *AttachmentsRequest, opts ...grpc.CallOption) (*AttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachmentsResponse)
	err := c.cc.Invoke(ctx, Grid_Attachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Region(ctx context.Context, in *RegionRequest, opts ...grpc.CallOption) (*RegionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegionInfo)
	err := c.cc.Invoke(ctx, Grid_Region_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Land(ctx context.Context, in *LandRequest, opts ...grpc.CallOption) (*LandInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LandInfo)
	err := c.cc.Invoke(ctx, Grid_Land_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Neighbours(ctx context.Context, in *NeighboursRequest, opts ...grpc.CallOption) (*NeighboursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NeighboursResponse)
	err := c.cc.Invoke(ctx, Grid_Neighbours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, Grid_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Cap(ctx context.Context, in *CapRequest, opts ...grpc.CallOption) (*CapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapResponse)
	err := c.cc.Invoke(ctx, Grid_Cap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Grid_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, Grid_Control_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MoveEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Grid_ServiceDesc.Streams[1], Grid_Move_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MoveRequest, MoveEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grid_MoveClient = grpc.ServerStreamingClient[MoveEvent]

func (c *gridClient) Face(ctx context.Context, in *FaceRequest, opts ...grpc.CallOption) (*FaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FaceResponse)
	err := c.cc.Invoke(ctx, Grid_Face_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Halt(ctx context.Context, in *HaltRequest, opts ...grpc.CallOption) (*HaltResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HaltResponse)
	err := c.cc.Invoke(ctx, Grid_Halt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Friends(ctx context.Context, in *FriendsRequest, opts ...grpc.CallOption) (*FriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendsResponse)
	err := c.cc.Invoke(ctx, Grid_Friends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) NoteFriend(ctx context.Context, in *NoteFriendRequest, opts ...grpc.CallOption) (*NoteFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteFriendResponse)
	err := c.cc.Invoke(ctx, Grid_NoteFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) Handled(ctx context.Context, in *HandledRequest, opts ...grpc.CallOption) (*HandledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandledResponse)
	err := c.cc.Invoke(ctx, Grid_Handled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gridClient) ViewerCredential(ctx context.Context, in *ViewerCredentialRequest, opts ...grpc.CallOption) (*ViewerCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewerCredentialResponse)
	err := c.cc.Invoke(ctx, Grid_ViewerCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GridServer is the server API for Grid service.
// All implementations must embed UnimplementedGridServer
// for forward compatibility.
type GridServer interface {
	// Login authenticates a caller, BOTH WAYS, before anything else is
	// accepted. Two calls of one message type; see LoginRequest.
	//
	// slgod holds a live Second Life session, so an unauthenticated one
	// reachable off this machine is an open invitation to drive somebody
	// else's avatar. The exchange is the same one slrund uses, from the
	// same package.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Stream is the packet channel.  The client sends messages to put on
	// the circuit and receives the ones it has subscribed to.  Nothing
	// that is not a grid packet belongs here.
	Stream(grpc.BidiStreamingServer[ClientPacket, ServerPacket]) error
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Host brings a session up that is not running, and Logout puts one
	// down and keeps it down.
	//
	// Both are deliberate acts by a person, which is why they are their
	// own methods rather than something that happens as a side effect of
	// attaching.  Logging an avatar in is visible on the grid -- an
	// arrival, a presence, a notice to whoever is watching -- and should
	// not follow from a typo in a stale config file.
	//
	// Logout is remembered.  A session that was told to stop stays
	// stopped, so that somebody using that avatar in a viewer is not
	// fighting the daemon for it, and comes back only when asked for by
	// name.
	Host(context.Context, *HostRequest) (*HostResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// Presence reads where the avatar is and what it can see, and can
	// change the draw distance.
	//
	// Both belong to the server.  AgentUpdate is what puts a session in
	// the simulator's interest list, it has to keep being sent, and the
	// interest list is worked out from the camera rather than from where
	// the avatar is -- so a client that owned this would empty the
	// interest list for every other client by exiting.  A client can ask
	// what it is and ask for it to be changed; it cannot hold it.
	Presence(context.Context, *PresenceRequest) (*PresenceResponse, error)
	// Objects is what the region has told the session about itself.
	//
	// The server holds this for the same reason it holds the camera: a
	// region describes itself once, when the avatar arrives, and a
	// client that attaches a minute later is never told any of it.  The
	// server was there to hear it, so the server remembers.  It still
	// has no idea what any of the objects are for.
	Objects(context.Context, *ObjectsRequest) (*ObjectsResponse, error)
	// Attachments is what the simulator last said an avatar is wearing:
	// the attachment list at the end of AvatarAppearance.
	//
	// Held by the server for the reason Objects is.  The simulator sends
	// it unasked -- about other avatars when they arrive, about this one
	// when it is baked -- so a client that attached afterwards has no
	// other way to hear it.
	//
	// It is the simulator's own account, which the region's object
	// descriptions are not: a viewer keeps an avatar a cloud until what
	// it has been shown matches this list, and a client can tell "on,
	// and not described yet" from "not on" the same way.
	Attachments(context.Context, *AttachmentsRequest) (*AttachmentsResponse, error)
	// Region is what the simulator said about itself in the handshake,
	// which happens once, before any client is listening.
	Region(context.Context, *RegionRequest) (*RegionInfo, error)
	// Land is what the session was told about the ground it is on: the
	// parcel it was pushed on arrival, and the region's parcel overlay.
	//
	// Both arrive unasked, once, before any client is listening, and the
	// overlay is the half that cannot be asked for again -- four packets
	// on arrival and none afterwards, however politely a client asks.
	// The parcel can be asked for, in a tenth of a second, so only its
	// name and local id come back here: enough to say what the session
	// believes it is standing on when the asking fails or is not worth
	// the wait.
	Land(context.Context, *LandRequest) (*LandInfo, error)
	// Neighbours reads the circuits held to the regions AROUND that one,
	// and can turn them on and off.
	//
	// The same division as Presence, for the same reason.  A simulator
	// will not hand an avatar over a border to a client that holds no
	// circuit to the region on the other side, and holding one costs a
	// socket and a share of the traffic for as long as it is held -- so
	// it belongs to the server, which owns the circuits and pays for
	// them, and a client asks what it is and asks for it to be changed.
	//
	// Worth changing while a session is up, which is why this is not a
	// daemon-wide switch: one avatar is being driven by a person who
	// wants to walk out of the region, and the next is running a
	// benchmark that wants nothing but the region it is in.
	Neighbours(context.Context, *NeighboursRequest) (*NeighboursResponse, error)
	// Flush empties the object cache.
	//
	// It is done automatically when the region changes, since everything
	// cached then describes somewhere else.  This is for a client that
	// knows the cache is wrong for a reason the server cannot see.
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	// Cap makes an HTTP request against one of the agent's
	// capabilities.  The server holds the URLs and does the request; it
	// has no idea what any of them mean.  This is what keeps inventory,
	// asset upload and script compilation out of the server.
	Cap(context.Context, *CapRequest) (*CapResponse, error)
	// Send puts one message on the circuit without opening a stream, for
	// a client that only wants to say one thing.
	Send(context.Context, *SendRequest) (*SendResponse, error)
	// Control sends one AgentUpdate carrying control flags, and forgets
	// them.  Sitting on the ground and standing up are nothing but this.
	//
	// It belongs to the server for the reason Presence does, and more
	// sharply.  An AgentUpdate is not just its flags: it carries the
	// camera, its three axes and the draw distance, and the simulator
	// scopes its interest list by them.  A client has none of that -- it
	// knows a position from Presence and no axes at all -- so a client
	// that built one would be guessing at the camera and inventing a draw
	// distance, and the simulator would believe it until the server's own
	// update a second later put it back.  The server owns the camera, so
	// the server is the only thing that can send an update that is right
	// about everything except the one bit being asked for.
	//
	// A primitive rather than a sit call and a stand call, because it is
	// the same shape as everything else that moves an avatar: fly, stop,
	// jump, and the nudges a walk is made of.
	Control(context.Context, *ControlRequest) (*ControlResponse, error)
	// Move walks the avatar to a place in its region, and streams how it
	// is going until it is over.
	//
	// It belongs to the server for Control's reason and one more.  A walk
	// is a control flag held down on AgentUpdate, ten times a second,
	// with the body turned toward the target from where the avatar
	// actually is -- and the one that holds a flag down has to be the one
	// certain to let go of it.  A client that crashed mid-walk would leave
	// the last update it caused saying "forward", and the avatar would
	// walk until it met something.  The server steers, and a client that
	// goes away -- this stream ending, for any reason -- stops the avatar.
	//
	// The stream is a MoveEvent about every quarter of a second while the
	// avatar moves, and one final event, whose state is anything but
	// MOVING, after which it ends.  A walk that cannot start -- a target
	// outside the region, an avatar that is sitting, a viewer driving it
	// -- is that final event and nothing else, before anything is sent.
	//
	// One walk per avatar.  A second Move takes the first over without
	// stopping in between, and the first stream ends CANCELLED with the
	// reason "superseded"; Halt ends it with "halted" and stops the
	// avatar.
	//
	// It walks a straight line and avoids nothing.  What is in the way is
	// the client's to steer round, by asking again with a different
	// target; the server notices only that the avatar has stopped getting
	// closer, which is BLOCKED.
	Move(*MoveRequest, grpc.ServerStreamingServer[MoveEvent]) error
	// Face turns the avatar toward a place, or to a heading, without
	// moving it.  Every update after it keeps the facing, the server's
	// own once-a-second ones included.  A walk under way is ended by it,
	// as a superseded one.
	Face(context.Context, *FaceRequest) (*FaceResponse, error)
	// Halt ends any walk and stops the avatar.
	Halt(context.Context, *HaltRequest) (*HaltResponse, error)
	// Friends is who this avatar's friends are and which of them are
	// logged in.
	//
	// The server holds this for the same reason it holds the region's
	// objects: the grid says it once, to whoever was there. The list
	// itself arrives only in the login response -- it is on no message
	// the simulator ever sends -- and online status arrives as a burst
	// of OnlineNotification seconds after the handshake, long before a
	// client can attach. Neither can be asked for again.
	Friends(context.Context, *FriendsRequest) (*FriendsResponse, error)
	// NoteFriend records a friendship the client watched being formed.
	//
	// Accepting an offer is the one case the grid never reports. The
	// side that offers is told twice -- an instant message saying so
	// and an OnlineNotification -- and the side that accepts is told
	// nothing whatsoever, because it was the one that did it. A viewer
	// has the same hole and fills it the same way, by adding the friend
	// to its own list (LLAvatarTracker::formFriendship).
	//
	// So the client, which understands what it just sent, tells the
	// server, which holds what a client restart would lose. The server
	// still decodes nothing.
	NoteFriend(context.Context, *NoteFriendRequest) (*NoteFriendResponse, error)
	// Handled tells the server an offer it is keeping has been dealt
	// with -- accepted, declined, or put aside for good -- so that it
	// drops out of the record and out of every other client's list.
	//
	// The server keeps the offers that arrive for an avatar whether or
	// not anybody is attached: a teleport offered, a request to be
	// offered one, an item handed over, an offer of friendship, an
	// invitation into a group.  Each is answered by quoting an id that
	// arrives once and cannot be asked for again, and the daemon is the
	// one thing that is always there to hear it; a client that attaches
	// later is handed what is still waiting in Attached.offers.  That
	// makes this the second place the server reads a message body, after
	// the teleport and seat answers it reads for itself, and for the same
	// reason: it is the session's business whether or not anybody is
	// listening.
	//
	// A client calls it BEFORE sending its answer, and the answer says
	// whether to go on.  Two clients attached to one avatar see the same
	// offers, and the first to say it is dealing with one is the one
	// that does; the second is told who got there first and how, and
	// sends nothing.  A client whose answer then fails to go out calls
	// again with undo, and the offer is put back for everybody.
	Handled(context.Context, *HandledRequest) (*HandledResponse, error)
	// ViewerCredential mints a password a real viewer may log in with
	// ONCE, so that a session can be handed to a person without any
	// password being typed or stored anywhere.
	//
	// A call of its own rather than a field of StatusResponse because
	// asking is not free: every call makes a fresh secret and drops the
	// one before it, which is not something a client watching the
	// counters should do by accident.  Where the endpoint is and whether
	// a viewer is on it are facts and cost nothing to read, so they
	// travel in StatusResponse.viewer instead.
	ViewerCredential(context.Context, *ViewerCredentialRequest) (*ViewerCredentialResponse, error)
	mustEmbedUnimplementedGridServer()
}

// UnimplementedGridServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGridServer struct{}

func (UnimplementedGridServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGridServer) Stream(grpc.BidiStreamingServer[ClientPacket, ServerPacket]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGridServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedGridServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedGridServer) Host(context.Context, *HostRequest) (*HostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Host not implemented")
}
func (UnimplementedGridServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedGridServer) Presence(context.Context, *PresenceRequest) (*PresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Presence not implemented")
}
func (UnimplementedGridServer) Objects(context.Context, *ObjectsRequest) (*ObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Objects not implemented")
}
func (UnimplementedGridServer) Attachments(context.Context, *AttachmentsRequest) (*AttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Attachments not implemented")
}
func (UnimplementedGridServer) Region(context.Context, *RegionRequest) (*RegionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Region not implemented")
}
func (UnimplementedGridServer) Land(context.Context, *LandRequest) (*LandInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Land not implemented")
}
func (UnimplementedGridServer) Neighbours(context.Context, *NeighboursRequest) (*NeighboursResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Neighbours not implemented")
}
func (UnimplementedGridServer) Flush(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedGridServer) Cap(context.Context, *CapRequest) (*CapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cap not implemented")
}
func (UnimplementedGridServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedGridServer) Control(context.Context, *ControlRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedGridServer) Move(*MoveRequest, grpc.ServerStreamingServer[MoveEvent]) error {
	return status.Error(codes.Unimplemented, "method Move not implemented")
}
func (UnimplementedGridServer) Face(context.Context, *FaceRequest) (*FaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Face not implemented")
}
func (UnimplementedGridServer) Halt(context.Context, *HaltRequest) (*HaltResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Halt not implemented")
}
func (UnimplementedGridServer) Friends(context.Context, *FriendsRequest) (*FriendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Friends not implemented")
}
func (UnimplementedGridServer) NoteFriend(context.Context, *NoteFriendRequest) (*NoteFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NoteFriend not implemented")
}
func (UnimplementedGridServer) Handled(context.Context, *HandledRequest) (*HandledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handled not implemented")
}
func (UnimplementedGridServer) ViewerCredential(context.Context, *ViewerCredentialRequest) (*ViewerCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ViewerCredential not implemented")
}
func (UnimplementedGridServer) mustEmbedUnimplementedGridServer() {}
func (UnimplementedGridServer) testEmbeddedByValue()              {}

// UnsafeGridServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GridServer will
// result in compilation errors.
type UnsafeGridServer interface {
	mustEmbedUnimplementedGridServer()
}

func RegisterGridServer(s grpc.ServiceRegistrar, srv GridServer) {
	// If the following call panics, it indicates UnimplementedGridServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Grid_ServiceDesc, srv)
}

func _Grid_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GridServer).Stream(&grpc.GenericServerStream[ClientPacket, ServerPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grid_StreamServer = grpc.BidiStreamingServer[ClientPacket, ServerPacket]

func _Grid_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Host_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Host(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Host_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Host(ctx, req.(*HostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Presence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Presence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Presence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Presence(ctx, req.(*PresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Objects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Objects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Objects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Objects(ctx, req.(*ObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Attachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Attachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Attachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Attachments(ctx, req.(*AttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Region_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Region(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Region_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Region(ctx, req.(*RegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Land_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Land(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Land_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Land(ctx, req.(*LandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Neighbours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NeighboursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Neighbours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Neighbours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Neighbours(ctx, req.(*NeighboursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Cap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Cap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Cap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Cap(ctx, req.(*CapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Control_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Control(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Control_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Control(ctx, req.(*ControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Move_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MoveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GridServer).Move(m, &grpc.GenericServerStream[MoveRequest, MoveEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grid_MoveServer = grpc.ServerStreamingServer[MoveEvent]

func _Grid_Face_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Face(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Face_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Face(ctx, req.(*FaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Halt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HaltRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Halt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Halt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Halt(ctx, req.(*HaltRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Friends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Friends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Friends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Friends(ctx, req.(*FriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_NoteFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).NoteFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_NoteFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).NoteFriend(ctx, req.(*NoteFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_Handled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).Handled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_Handled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).Handled(ctx, req.(*HandledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grid_ViewerCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewerCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GridServer).ViewerCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grid_ViewerCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GridServer).ViewerCredential(ctx, req.(*ViewerCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Grid_ServiceDesc is the grpc.ServiceDesc for Grid service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grid_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slgo.v1.Grid",
	HandlerType: (*GridServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Grid_Login_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _Grid_ListAgents_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Grid_Status_Handler,
		},
		{
			MethodName: "Host",
			Handler:    _Grid_Host_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Grid_Logout_Handler,
		},
		{
			MethodName: "Presence",
			Handler:    _Grid_Presence_Handler,
		},
		{
			MethodName: "Objects",
			Handler:    _Grid_Objects_Handler,
		},
		{
			MethodName: "Attachments",
			Handler:    _Grid_Attachments_Handler,
		},
		{
			MethodName: "Region",
			Handler:    _Grid_Region_Handler,
		},
		{
			MethodName: "Land",
			Handler:    _Grid_Land_Handler,
		},
		{
			MethodName: "Neighbours",
			Handler:    _Grid_Neighbours_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _Grid_Flush_Handler,
		},
		{
			MethodName: "Cap",
			Handler:    _Grid_Cap_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Grid_Send_Handler,
		},
		{
			MethodName: "Control",
			Handler:    _Grid_Control_Handler,
		},
		{
			MethodName: "Face",
			Handler:    _Grid_Face_Handler,
		},
		{
			MethodName: "Halt",
			Handler:    _Grid_Halt_Handler,
		},
		{
			MethodName: "Friends",
			Handler:    _Grid_Friends_Handler,
		},
		{
			MethodName: "NoteFriend",
			Handler:    _Grid_NoteFriend_Handler,
		},
		{
			MethodName: "Handled",
			Handler:    _Grid_Handled_Handler,
		},
		{
			MethodName: "ViewerCredential",
			Handler:    _Grid_ViewerCredential_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Grid_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Move",
			Handler:       _Grid_Move_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "slgo.proto",
}
